// Copyright 2025 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/assessment/assessment.proto

package assessmentconnect

import (
	assessment "confirmate.io/core/api/assessment"
	connect "connectrpc.com/connect/v2"
	context "context"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	sync "sync"
)

const (
	// AssessmentName is the fully-qualified name of the Assessment service.
	AssessmentName = "confirmate.assessment.v1.Assessment"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssessmentCalculateComplianceProcedure is the procedure name of the Assessment's
	// CalculateCompliance RPC.
	AssessmentCalculateComplianceProcedure = "/confirmate.assessment.v1.Assessment/CalculateCompliance"
	// AssessmentAssessEvidenceProcedure is the procedure name of the Assessment's AssessEvidence RPC.
	AssessmentAssessEvidenceProcedure = "/confirmate.assessment.v1.Assessment/AssessEvidence"
	// AssessmentAssessEvidencesProcedure is the procedure name of the Assessment's AssessEvidences RPC.
	AssessmentAssessEvidencesProcedure = "/confirmate.assessment.v1.Assessment/AssessEvidences"
)

var (
	assessmentCalculateComplianceSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     assessment.File_api_assessment_assessment_proto.Services().ByName("Assessment").Methods().ByName("CalculateCompliance"),
			Procedure:  AssessmentCalculateComplianceProcedure,
		}
	})
	assessmentAssessEvidenceSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     assessment.File_api_assessment_assessment_proto.Services().ByName("Assessment").Methods().ByName("AssessEvidence"),
			Procedure:  AssessmentAssessEvidenceProcedure,
		}
	})
	assessmentAssessEvidencesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeBidi,
			Schema:     assessment.File_api_assessment_assessment_proto.Services().ByName("Assessment").Methods().ByName("AssessEvidences"),
			Procedure:  AssessmentAssessEvidencesProcedure,
		}
	})
)

// AssessmentClient is a client for the confirmate.assessment.v1.Assessment service.
type AssessmentClient interface {
	// Triggers the compliance calculation. Part of the private API. Not exposed
	// as REST.
	CalculateCompliance(context.Context, *assessment.CalculateComplianceRequest) (*emptypb.Empty, error)
	// Assesses the evidence sent by the discovery. Part of the public API, also
	// exposed as REST.
	AssessEvidence(context.Context, *assessment.AssessEvidenceRequest) (*assessment.AssessEvidenceResponse, error)
	// Assesses stream of evidences sent by the discovery and returns a response
	// stream. Part of the public API. Not exposed as REST.
	AssessEvidences(context.Context) (AssessmentAssessEvidencesClientStream, error)
}

// NewAssessmentClient constructs a client for the confirmate.assessment.v1.Assessment service.
// Multiple service clients may share a single connect.Client.
func NewAssessmentClient(client *connect.Client) AssessmentClient {
	return &assessmentClient{client: client}
}

// AssessmentAssessEvidencesClientStream is the client stream for the Assessment's AssessEvidences
// RPC.
type AssessmentAssessEvidencesClientStream struct {
	stream connect.ClientStream
}

// SendHeaders opens the stream and flushes the request headers without a message. The first Send or
// Receive does this implicitly.
func (s AssessmentAssessEvidencesClientStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a request message to the server.
func (s AssessmentAssessEvidencesClientStream) Send(req *assessment.AssessEvidenceRequest) error {
	return s.stream.Send(req)
}

// CloseSend closes the request side of the stream.
func (s AssessmentAssessEvidencesClientStream) CloseSend() error {
	return s.stream.CloseSend()
}

// Receive returns the next response message from the server.
func (s AssessmentAssessEvidencesClientStream) Receive() (*assessment.AssessEvidencesResponse, error) {
	var res assessment.AssessEvidencesResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s AssessmentAssessEvidencesClientStream) Close() error {
	return s.stream.Close()
}

// AssessmentHandler is an implementation of the confirmate.assessment.v1.Assessment service.
type AssessmentHandler interface {
	// Triggers the compliance calculation. Part of the private API. Not exposed
	// as REST.
	CalculateCompliance(context.Context, *assessment.CalculateComplianceRequest) (*emptypb.Empty, error)
	// Assesses the evidence sent by the discovery. Part of the public API, also
	// exposed as REST.
	AssessEvidence(context.Context, *assessment.AssessEvidenceRequest) (*assessment.AssessEvidenceResponse, error)
	// Assesses stream of evidences sent by the discovery and returns a response
	// stream. Part of the public API. Not exposed as REST.
	AssessEvidences(context.Context, AssessmentAssessEvidencesServerStream) error
}

// RegisterAssessmentHandler registers svc as the confirmate.assessment.v1.Assessment implementation
// on server.
func RegisterAssessmentHandler(server *connect.Server, svc AssessmentHandler) {
	adapter := assessmentHandler{svc: svc}
	server.Register(
		connect.Method{Spec: assessmentCalculateComplianceSpec(), Handler: adapter.calculateCompliance},
		connect.Method{Spec: assessmentAssessEvidenceSpec(), Handler: adapter.assessEvidence},
		connect.Method{Spec: assessmentAssessEvidencesSpec(), Handler: adapter.assessEvidences},
	)
}

// AssessmentAssessEvidencesServerStream is the server stream for the Assessment's AssessEvidences
// RPC.
type AssessmentAssessEvidencesServerStream struct {
	stream connect.ServerStream
}

// Receive returns the next request message from the client.
func (s AssessmentAssessEvidencesServerStream) Receive() (*assessment.AssessEvidenceRequest, error) {
	var req assessment.AssessEvidenceRequest
	if err := s.stream.Receive(&req); err != nil {
		return nil, err
	}
	return &req, nil
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s AssessmentAssessEvidencesServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s AssessmentAssessEvidencesServerStream) Send(res *assessment.AssessEvidencesResponse) error {
	return s.stream.Send(res)
}

// UnimplementedAssessmentHandler returns CodeUnimplemented from all methods.
type UnimplementedAssessmentHandler struct{}

func (UnimplementedAssessmentHandler) CalculateCompliance(context.Context, *assessment.CalculateComplianceRequest) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.assessment.v1.Assessment.CalculateCompliance is not implemented")
}

func (UnimplementedAssessmentHandler) AssessEvidence(context.Context, *assessment.AssessEvidenceRequest) (*assessment.AssessEvidenceResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.assessment.v1.Assessment.AssessEvidence is not implemented")
}

func (UnimplementedAssessmentHandler) AssessEvidences(context.Context, AssessmentAssessEvidencesServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "confirmate.assessment.v1.Assessment.AssessEvidences is not implemented")
}

type assessmentClient struct {
	client *connect.Client
}

func (c *assessmentClient) CalculateCompliance(ctx context.Context, req *assessment.CalculateComplianceRequest) (*emptypb.Empty, error) {
	var res emptypb.Empty
	if err := c.client.CallUnary(ctx, assessmentCalculateComplianceSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *assessmentClient) AssessEvidence(ctx context.Context, req *assessment.AssessEvidenceRequest) (*assessment.AssessEvidenceResponse, error) {
	var res assessment.AssessEvidenceResponse
	if err := c.client.CallUnary(ctx, assessmentAssessEvidenceSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *assessmentClient) AssessEvidences(ctx context.Context) (AssessmentAssessEvidencesClientStream, error) {
	stream, err := c.client.CallClientStream(ctx, assessmentAssessEvidencesSpec())
	if err != nil {
		return AssessmentAssessEvidencesClientStream{}, err
	}
	return AssessmentAssessEvidencesClientStream{stream: stream}, nil
}

type assessmentHandler struct{ svc AssessmentHandler }

func (h assessmentHandler) calculateCompliance(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req assessment.CalculateComplianceRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.CalculateCompliance(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h assessmentHandler) assessEvidence(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req assessment.AssessEvidenceRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.AssessEvidence(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h assessmentHandler) assessEvidences(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	return h.svc.AssessEvidences(ctx, AssessmentAssessEvidencesServerStream{stream: stream})
}
