// Copyright 2025 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/assessment/assessment.proto

package assessment

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"

	evidence "confirmate.io/core/api/evidence"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureAssessmentRequest) Reset() {
	*x = ConfigureAssessmentRequest{}
	mi := &file_api_assessment_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAssessmentRequest) ProtoMessage() {}

func (x *ConfigureAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAssessmentRequest.ProtoReflect.Descriptor instead.
func (*ConfigureAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{0}
}

type ConfigureAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureAssessmentResponse) Reset() {
	*x = ConfigureAssessmentResponse{}
	mi := &file_api_assessment_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAssessmentResponse) ProtoMessage() {}

func (x *ConfigureAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAssessmentResponse.ProtoReflect.Descriptor instead.
func (*ConfigureAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{1}
}

type CalculateComplianceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlId     string                 `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateComplianceRequest) Reset() {
	*x = CalculateComplianceRequest{}
	mi := &file_api_assessment_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateComplianceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateComplianceRequest) ProtoMessage() {}

func (x *CalculateComplianceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateComplianceRequest.ProtoReflect.Descriptor instead.
func (*CalculateComplianceRequest) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateComplianceRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

type AssessEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      *evidence.Evidence     `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessEvidenceRequest) Reset() {
	*x = AssessEvidenceRequest{}
	mi := &file_api_assessment_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessEvidenceRequest) ProtoMessage() {}

func (x *AssessEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessEvidenceRequest.ProtoReflect.Descriptor instead.
func (*AssessEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *AssessEvidenceRequest) GetEvidence() *evidence.Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// AssessEvidenceResponse belongs to AssessEvidence, which uses a custom unary
// RPC and therefore requires a response message according to the style
// convention. Since no return values are required, this is empty.
type AssessEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AssessmentStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=confirmate.assessment.v1.AssessmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessEvidenceResponse) Reset() {
	*x = AssessEvidenceResponse{}
	mi := &file_api_assessment_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessEvidenceResponse) ProtoMessage() {}

func (x *AssessEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessEvidenceResponse.ProtoReflect.Descriptor instead.
func (*AssessEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *AssessEvidenceResponse) GetStatus() AssessmentStatus {
	if x != nil {
		return x.Status
	}
	return AssessmentStatus_ASSESSMENT_STATUS_UNSPECIFIED
}

// AssessEvidencesResponse belongs to AssessEvidences, which uses a custom
// bidirectional streaming RPC and therefore requires a response message
// according to the style convention. The bidirectional streaming needs the
// status and its message in the response for error handling.
type AssessEvidencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AssessmentStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=confirmate.assessment.v1.AssessmentStatus" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessEvidencesResponse) Reset() {
	*x = AssessEvidencesResponse{}
	mi := &file_api_assessment_assessment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessEvidencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessEvidencesResponse) ProtoMessage() {}

func (x *AssessEvidencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_assessment_assessment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessEvidencesResponse.ProtoReflect.Descriptor instead.
func (*AssessEvidencesResponse) Descriptor() ([]byte, []int) {
	return file_api_assessment_assessment_proto_rawDescGZIP(), []int{5}
}

func (x *AssessEvidencesResponse) GetStatus() AssessmentStatus {
	if x != nil {
		return x.Status
	}
	return AssessmentStatus_ASSESSMENT_STATUS_UNSPECIFIED
}

func (x *AssessEvidencesResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_api_assessment_assessment_proto protoreflect.FileDescriptor

const file_api_assessment_assessment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/assessment/assessment.proto\x12\x18confirmate.assessment.v1\x1a\x1bapi/assessment/metric.proto\x1a\x1bapi/evidence/evidence.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\x1a\x1bapi/assessment/result.proto\"\x1c\n" +
	"\x1aConfigureAssessmentRequest\"\x1d\n" +
	"\x1bConfigureAssessmentResponse\";\n" +
	"\x1aCalculateComplianceRequest\x12\x1d\n" +
	"\n" +
	"control_id\x18\x01 \x01(\tR\tcontrolId\"]\n" +
	"\x15AssessEvidenceRequest\x12D\n" +
	"\bevidence\x18\x01 \x01(\v2 .confirmate.evidence.v1.EvidenceB\x06\xbaH\x03\xc8\x01\x01R\bevidence\"\\\n" +
	"\x16AssessEvidenceResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.confirmate.assessment.v1.AssessmentStatusR\x06status\"\x84\x01\n" +
	"\x17AssessEvidencesResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.confirmate.assessment.v1.AssessmentStatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage2\x92\x03\n" +
	"\n" +
	"Assessment\x12e\n" +
	"\x13CalculateCompliance\x124.confirmate.assessment.v1.CalculateComplianceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x9f\x01\n" +
	"\x0eAssessEvidence\x12/.confirmate.assessment.v1.AssessEvidenceRequest\x1a0.confirmate.assessment.v1.AssessEvidenceResponse\"*\x82\xd3\xe4\x93\x02$:\bevidence\"\x18/v1/assessment/evidences\x12{\n" +
	"\x0fAssessEvidences\x12/.confirmate.assessment.v1.AssessEvidenceRequest\x1a1.confirmate.assessment.v1.AssessEvidencesResponse\"\x00(\x010\x01B#Z!confirmate.io/core/api/assessmentb\x06proto3"

var (
	file_api_assessment_assessment_proto_rawDescOnce sync.Once
	file_api_assessment_assessment_proto_rawDescData []byte
)

func file_api_assessment_assessment_proto_rawDescGZIP() []byte {
	file_api_assessment_assessment_proto_rawDescOnce.Do(func() {
		file_api_assessment_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_assessment_assessment_proto_rawDesc), len(file_api_assessment_assessment_proto_rawDesc)))
	})
	return file_api_assessment_assessment_proto_rawDescData
}

var file_api_assessment_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_assessment_assessment_proto_goTypes = []any{
	(*ConfigureAssessmentRequest)(nil),  // 0: confirmate.assessment.v1.ConfigureAssessmentRequest
	(*ConfigureAssessmentResponse)(nil), // 1: confirmate.assessment.v1.ConfigureAssessmentResponse
	(*CalculateComplianceRequest)(nil),  // 2: confirmate.assessment.v1.CalculateComplianceRequest
	(*AssessEvidenceRequest)(nil),       // 3: confirmate.assessment.v1.AssessEvidenceRequest
	(*AssessEvidenceResponse)(nil),      // 4: confirmate.assessment.v1.AssessEvidenceResponse
	(*AssessEvidencesResponse)(nil),     // 5: confirmate.assessment.v1.AssessEvidencesResponse
	(*evidence.Evidence)(nil),           // 6: confirmate.evidence.v1.Evidence
	(AssessmentStatus)(0),               // 7: confirmate.assessment.v1.AssessmentStatus
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_api_assessment_assessment_proto_depIdxs = []int32{
	6, // 0: confirmate.assessment.v1.AssessEvidenceRequest.evidence:type_name -> confirmate.evidence.v1.Evidence
	7, // 1: confirmate.assessment.v1.AssessEvidenceResponse.status:type_name -> confirmate.assessment.v1.AssessmentStatus
	7, // 2: confirmate.assessment.v1.AssessEvidencesResponse.status:type_name -> confirmate.assessment.v1.AssessmentStatus
	2, // 3: confirmate.assessment.v1.Assessment.CalculateCompliance:input_type -> confirmate.assessment.v1.CalculateComplianceRequest
	3, // 4: confirmate.assessment.v1.Assessment.AssessEvidence:input_type -> confirmate.assessment.v1.AssessEvidenceRequest
	3, // 5: confirmate.assessment.v1.Assessment.AssessEvidences:input_type -> confirmate.assessment.v1.AssessEvidenceRequest
	8, // 6: confirmate.assessment.v1.Assessment.CalculateCompliance:output_type -> google.protobuf.Empty
	4, // 7: confirmate.assessment.v1.Assessment.AssessEvidence:output_type -> confirmate.assessment.v1.AssessEvidenceResponse
	5, // 8: confirmate.assessment.v1.Assessment.AssessEvidences:output_type -> confirmate.assessment.v1.AssessEvidencesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_assessment_assessment_proto_init() }
func file_api_assessment_assessment_proto_init() {
	if File_api_assessment_assessment_proto != nil {
		return
	}
	file_api_assessment_metric_proto_init()
	file_api_assessment_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_assessment_assessment_proto_rawDesc), len(file_api_assessment_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_assessment_assessment_proto_goTypes,
		DependencyIndexes: file_api_assessment_assessment_proto_depIdxs,
		MessageInfos:      file_api_assessment_assessment_proto_msgTypes,
	}.Build()
	File_api_assessment_assessment_proto = out.File
	file_api_assessment_assessment_proto_goTypes = nil
	file_api_assessment_assessment_proto_depIdxs = nil
}
