// Copyright 2016-2025 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/evidence/evidence_store.proto

package evidenceconnect

import (
	evidence "confirmate.io/core/api/evidence"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// EvidenceStoreName is the fully-qualified name of the EvidenceStore service.
	EvidenceStoreName = "confirmate.evidence.v1.EvidenceStore"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EvidenceStoreStoreEvidenceProcedure is the procedure name of the EvidenceStore's StoreEvidence
	// RPC.
	EvidenceStoreStoreEvidenceProcedure = "/confirmate.evidence.v1.EvidenceStore/StoreEvidence"
	// EvidenceStoreStoreEvidencesProcedure is the procedure name of the EvidenceStore's StoreEvidences
	// RPC.
	EvidenceStoreStoreEvidencesProcedure = "/confirmate.evidence.v1.EvidenceStore/StoreEvidences"
	// EvidenceStoreListEvidencesProcedure is the procedure name of the EvidenceStore's ListEvidences
	// RPC.
	EvidenceStoreListEvidencesProcedure = "/confirmate.evidence.v1.EvidenceStore/ListEvidences"
	// EvidenceStoreGetEvidenceProcedure is the procedure name of the EvidenceStore's GetEvidence RPC.
	EvidenceStoreGetEvidenceProcedure = "/confirmate.evidence.v1.EvidenceStore/GetEvidence"
	// EvidenceStoreListSupportedResourceTypesProcedure is the procedure name of the EvidenceStore's
	// ListSupportedResourceTypes RPC.
	EvidenceStoreListSupportedResourceTypesProcedure = "/confirmate.evidence.v1.EvidenceStore/ListSupportedResourceTypes"
	// EvidenceStoreListResourcesProcedure is the procedure name of the EvidenceStore's ListResources
	// RPC.
	EvidenceStoreListResourcesProcedure = "/confirmate.evidence.v1.EvidenceStore/ListResources"
	// EvidenceStoreListToolsProcedure is the procedure name of the EvidenceStore's ListTools RPC.
	EvidenceStoreListToolsProcedure = "/confirmate.evidence.v1.EvidenceStore/ListTools"
)

var (
	evidenceStoreStoreEvidenceSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("StoreEvidence"),
			Procedure:  EvidenceStoreStoreEvidenceProcedure,
		}
	})
	evidenceStoreStoreEvidencesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeBidi,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("StoreEvidences"),
			Procedure:  EvidenceStoreStoreEvidencesProcedure,
		}
	})
	evidenceStoreListEvidencesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("ListEvidences"),
			Procedure:  EvidenceStoreListEvidencesProcedure,
		}
	})
	evidenceStoreGetEvidenceSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("GetEvidence"),
			Procedure:  EvidenceStoreGetEvidenceProcedure,
		}
	})
	evidenceStoreListSupportedResourceTypesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("ListSupportedResourceTypes"),
			Procedure:  EvidenceStoreListSupportedResourceTypesProcedure,
		}
	})
	evidenceStoreListResourcesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("ListResources"),
			Procedure:  EvidenceStoreListResourcesProcedure,
		}
	})
	evidenceStoreListToolsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_store_proto.Services().ByName("EvidenceStore").Methods().ByName("ListTools"),
			Procedure:  EvidenceStoreListToolsProcedure,
		}
	})
)

// EvidenceStoreClient is a client for the confirmate.evidence.v1.EvidenceStore service.
type EvidenceStoreClient interface {
	// Stores an evidence to the evidence storage. Part of the public API, also
	// exposed as REST.
	StoreEvidence(context.Context, *evidence.StoreEvidenceRequest) (*evidence.StoreEvidenceResponse, error)
	// Stores a stream of evidences to the evidence storage and returns a response
	// stream. Part of the public API, not exposed as REST.
	StoreEvidences(context.Context) (EvidenceStoreStoreEvidencesClientStream, error)
	// Returns all stored evidences. Part of the public API, also exposed as REST.
	ListEvidences(context.Context, *evidence.ListEvidencesRequest) (*evidence.ListEvidencesResponse, error)
	// Returns a particular stored evidence. Part of the public API, also exposed
	// as REST.
	GetEvidence(context.Context, *evidence.GetEvidenceRequest) (*evidence.Evidence, error)
	// Returns the resource types that are supported by the EvidenceStore.
	ListSupportedResourceTypes(context.Context, *evidence.ListSupportedResourceTypesRequest) (*evidence.ListSupportedResourceTypesResponse, error)
	// Lists all resources collected in the last run, exposed as REST.
	ListResources(context.Context, *evidence.ListResourcesRequest) (*evidence.ListResourcesResponse, error)
	// Returns the IDs of all evidence collecting tools that have provided
	// evidence so far. Part of the public API, also exposed as REST.
	ListTools(context.Context, *evidence.ListToolsRequest) (*evidence.ListToolsResponse, error)
}

// NewEvidenceStoreClient constructs a client for the confirmate.evidence.v1.EvidenceStore service.
// Multiple service clients may share a single connect.Client.
func NewEvidenceStoreClient(client *connect.Client) EvidenceStoreClient {
	return &evidenceStoreClient{client: client}
}

// EvidenceStoreStoreEvidencesClientStream is the client stream for the EvidenceStore's
// StoreEvidences RPC.
type EvidenceStoreStoreEvidencesClientStream struct {
	stream connect.ClientStream
}

// SendHeaders opens the stream and flushes the request headers without a message. The first Send or
// Receive does this implicitly.
func (s EvidenceStoreStoreEvidencesClientStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a request message to the server.
func (s EvidenceStoreStoreEvidencesClientStream) Send(req *evidence.StoreEvidenceRequest) error {
	return s.stream.Send(req)
}

// CloseSend closes the request side of the stream.
func (s EvidenceStoreStoreEvidencesClientStream) CloseSend() error {
	return s.stream.CloseSend()
}

// Receive returns the next response message from the server.
func (s EvidenceStoreStoreEvidencesClientStream) Receive() (*evidence.StoreEvidencesResponse, error) {
	var res evidence.StoreEvidencesResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s EvidenceStoreStoreEvidencesClientStream) Close() error {
	return s.stream.Close()
}

// EvidenceStoreHandler is an implementation of the confirmate.evidence.v1.EvidenceStore service.
type EvidenceStoreHandler interface {
	// Stores an evidence to the evidence storage. Part of the public API, also
	// exposed as REST.
	StoreEvidence(context.Context, *evidence.StoreEvidenceRequest) (*evidence.StoreEvidenceResponse, error)
	// Stores a stream of evidences to the evidence storage and returns a response
	// stream. Part of the public API, not exposed as REST.
	StoreEvidences(context.Context, EvidenceStoreStoreEvidencesServerStream) error
	// Returns all stored evidences. Part of the public API, also exposed as REST.
	ListEvidences(context.Context, *evidence.ListEvidencesRequest) (*evidence.ListEvidencesResponse, error)
	// Returns a particular stored evidence. Part of the public API, also exposed
	// as REST.
	GetEvidence(context.Context, *evidence.GetEvidenceRequest) (*evidence.Evidence, error)
	// Returns the resource types that are supported by the EvidenceStore.
	ListSupportedResourceTypes(context.Context, *evidence.ListSupportedResourceTypesRequest) (*evidence.ListSupportedResourceTypesResponse, error)
	// Lists all resources collected in the last run, exposed as REST.
	ListResources(context.Context, *evidence.ListResourcesRequest) (*evidence.ListResourcesResponse, error)
	// Returns the IDs of all evidence collecting tools that have provided
	// evidence so far. Part of the public API, also exposed as REST.
	ListTools(context.Context, *evidence.ListToolsRequest) (*evidence.ListToolsResponse, error)
}

// RegisterEvidenceStoreHandler registers svc as the confirmate.evidence.v1.EvidenceStore
// implementation on server.
func RegisterEvidenceStoreHandler(server *connect.Server, svc EvidenceStoreHandler) {
	adapter := evidenceStoreHandler{svc: svc}
	server.Register(
		connect.Method{Spec: evidenceStoreStoreEvidenceSpec(), Handler: adapter.storeEvidence},
		connect.Method{Spec: evidenceStoreStoreEvidencesSpec(), Handler: adapter.storeEvidences},
		connect.Method{Spec: evidenceStoreListEvidencesSpec(), Handler: adapter.listEvidences},
		connect.Method{Spec: evidenceStoreGetEvidenceSpec(), Handler: adapter.getEvidence},
		connect.Method{Spec: evidenceStoreListSupportedResourceTypesSpec(), Handler: adapter.listSupportedResourceTypes},
		connect.Method{Spec: evidenceStoreListResourcesSpec(), Handler: adapter.listResources},
		connect.Method{Spec: evidenceStoreListToolsSpec(), Handler: adapter.listTools},
	)
}

// EvidenceStoreStoreEvidencesServerStream is the server stream for the EvidenceStore's
// StoreEvidences RPC.
type EvidenceStoreStoreEvidencesServerStream struct {
	stream connect.ServerStream
}

// Receive returns the next request message from the client.
func (s EvidenceStoreStoreEvidencesServerStream) Receive() (*evidence.StoreEvidenceRequest, error) {
	var req evidence.StoreEvidenceRequest
	if err := s.stream.Receive(&req); err != nil {
		return nil, err
	}
	return &req, nil
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s EvidenceStoreStoreEvidencesServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s EvidenceStoreStoreEvidencesServerStream) Send(res *evidence.StoreEvidencesResponse) error {
	return s.stream.Send(res)
}

// UnimplementedEvidenceStoreHandler returns CodeUnimplemented from all methods.
type UnimplementedEvidenceStoreHandler struct{}

func (UnimplementedEvidenceStoreHandler) StoreEvidence(context.Context, *evidence.StoreEvidenceRequest) (*evidence.StoreEvidenceResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.StoreEvidence is not implemented")
}

func (UnimplementedEvidenceStoreHandler) StoreEvidences(context.Context, EvidenceStoreStoreEvidencesServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.StoreEvidences is not implemented")
}

func (UnimplementedEvidenceStoreHandler) ListEvidences(context.Context, *evidence.ListEvidencesRequest) (*evidence.ListEvidencesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.ListEvidences is not implemented")
}

func (UnimplementedEvidenceStoreHandler) GetEvidence(context.Context, *evidence.GetEvidenceRequest) (*evidence.Evidence, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.GetEvidence is not implemented")
}

func (UnimplementedEvidenceStoreHandler) ListSupportedResourceTypes(context.Context, *evidence.ListSupportedResourceTypesRequest) (*evidence.ListSupportedResourceTypesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.ListSupportedResourceTypes is not implemented")
}

func (UnimplementedEvidenceStoreHandler) ListResources(context.Context, *evidence.ListResourcesRequest) (*evidence.ListResourcesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.ListResources is not implemented")
}

func (UnimplementedEvidenceStoreHandler) ListTools(context.Context, *evidence.ListToolsRequest) (*evidence.ListToolsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.EvidenceStore.ListTools is not implemented")
}

type evidenceStoreClient struct {
	client *connect.Client
}

func (c *evidenceStoreClient) StoreEvidence(ctx context.Context, req *evidence.StoreEvidenceRequest) (*evidence.StoreEvidenceResponse, error) {
	var res evidence.StoreEvidenceResponse
	if err := c.client.CallUnary(ctx, evidenceStoreStoreEvidenceSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *evidenceStoreClient) StoreEvidences(ctx context.Context) (EvidenceStoreStoreEvidencesClientStream, error) {
	stream, err := c.client.CallClientStream(ctx, evidenceStoreStoreEvidencesSpec())
	if err != nil {
		return EvidenceStoreStoreEvidencesClientStream{}, err
	}
	return EvidenceStoreStoreEvidencesClientStream{stream: stream}, nil
}

func (c *evidenceStoreClient) ListEvidences(ctx context.Context, req *evidence.ListEvidencesRequest) (*evidence.ListEvidencesResponse, error) {
	var res evidence.ListEvidencesResponse
	if err := c.client.CallUnary(ctx, evidenceStoreListEvidencesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *evidenceStoreClient) GetEvidence(ctx context.Context, req *evidence.GetEvidenceRequest) (*evidence.Evidence, error) {
	var res evidence.Evidence
	if err := c.client.CallUnary(ctx, evidenceStoreGetEvidenceSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *evidenceStoreClient) ListSupportedResourceTypes(ctx context.Context, req *evidence.ListSupportedResourceTypesRequest) (*evidence.ListSupportedResourceTypesResponse, error) {
	var res evidence.ListSupportedResourceTypesResponse
	if err := c.client.CallUnary(ctx, evidenceStoreListSupportedResourceTypesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *evidenceStoreClient) ListResources(ctx context.Context, req *evidence.ListResourcesRequest) (*evidence.ListResourcesResponse, error) {
	var res evidence.ListResourcesResponse
	if err := c.client.CallUnary(ctx, evidenceStoreListResourcesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *evidenceStoreClient) ListTools(ctx context.Context, req *evidence.ListToolsRequest) (*evidence.ListToolsResponse, error) {
	var res evidence.ListToolsResponse
	if err := c.client.CallUnary(ctx, evidenceStoreListToolsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type evidenceStoreHandler struct{ svc EvidenceStoreHandler }

func (h evidenceStoreHandler) storeEvidence(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.StoreEvidenceRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.StoreEvidence(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h evidenceStoreHandler) storeEvidences(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	return h.svc.StoreEvidences(ctx, EvidenceStoreStoreEvidencesServerStream{stream: stream})
}

func (h evidenceStoreHandler) listEvidences(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.ListEvidencesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListEvidences(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h evidenceStoreHandler) getEvidence(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.GetEvidenceRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetEvidence(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h evidenceStoreHandler) listSupportedResourceTypes(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.ListSupportedResourceTypesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListSupportedResourceTypes(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h evidenceStoreHandler) listResources(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.ListResourcesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListResources(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h evidenceStoreHandler) listTools(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.ListToolsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListTools(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
