// Copyright 2025-2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/evidence/evidence.proto

package evidenceconnect

import (
	evidence "confirmate.io/core/api/evidence"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// ResourcesName is the fully-qualified name of the Resources service.
	ResourcesName = "confirmate.evidence.v1.Resources"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourcesUpdateResourceProcedure is the procedure name of the Resources's UpdateResource RPC.
	ResourcesUpdateResourceProcedure = "/confirmate.evidence.v1.Resources/UpdateResource"
	// ResourcesListGraphEdgesProcedure is the procedure name of the Resources's ListGraphEdges RPC.
	ResourcesListGraphEdgesProcedure = "/confirmate.evidence.v1.Resources/ListGraphEdges"
)

var (
	resourcesUpdateResourceSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_proto.Services().ByName("Resources").Methods().ByName("UpdateResource"),
			Procedure:  ResourcesUpdateResourceProcedure,
		}
	})
	resourcesListGraphEdgesSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     evidence.File_api_evidence_evidence_proto.Services().ByName("Resources").Methods().ByName("ListGraphEdges"),
			Procedure:  ResourcesListGraphEdgesProcedure,
		}
	})
)

// ResourcesClient is a client for the confirmate.evidence.v1.Resources service.
type ResourcesClient interface {
	// UpdateResource updates a resource (or creates it, if it does not exist).
	// This is used to give third-party tools the possibility to add something to
	// the resource graph.
	UpdateResource(context.Context, *evidence.UpdateResourceRequest) (*evidence.ResourceSnapshot, error)
	// ListGraphEdges returns the edges (relationship) between resources in our
	// resource graph.
	ListGraphEdges(context.Context, *evidence.ListGraphEdgesRequest) (*evidence.ListGraphEdgesResponse, error)
}

// NewResourcesClient constructs a client for the confirmate.evidence.v1.Resources service. Multiple
// service clients may share a single connect.Client.
func NewResourcesClient(client *connect.Client) ResourcesClient {
	return &resourcesClient{client: client}
}

// ResourcesHandler is an implementation of the confirmate.evidence.v1.Resources service.
type ResourcesHandler interface {
	// UpdateResource updates a resource (or creates it, if it does not exist).
	// This is used to give third-party tools the possibility to add something to
	// the resource graph.
	UpdateResource(context.Context, *evidence.UpdateResourceRequest) (*evidence.ResourceSnapshot, error)
	// ListGraphEdges returns the edges (relationship) between resources in our
	// resource graph.
	ListGraphEdges(context.Context, *evidence.ListGraphEdgesRequest) (*evidence.ListGraphEdgesResponse, error)
}

// RegisterResourcesHandler registers svc as the confirmate.evidence.v1.Resources implementation on
// server.
func RegisterResourcesHandler(server *connect.Server, svc ResourcesHandler) {
	adapter := resourcesHandler{svc: svc}
	server.Register(
		connect.Method{Spec: resourcesUpdateResourceSpec(), Handler: adapter.updateResource},
		connect.Method{Spec: resourcesListGraphEdgesSpec(), Handler: adapter.listGraphEdges},
	)
}

// UnimplementedResourcesHandler returns CodeUnimplemented from all methods.
type UnimplementedResourcesHandler struct{}

func (UnimplementedResourcesHandler) UpdateResource(context.Context, *evidence.UpdateResourceRequest) (*evidence.ResourceSnapshot, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.Resources.UpdateResource is not implemented")
}

func (UnimplementedResourcesHandler) ListGraphEdges(context.Context, *evidence.ListGraphEdgesRequest) (*evidence.ListGraphEdgesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "confirmate.evidence.v1.Resources.ListGraphEdges is not implemented")
}

type resourcesClient struct {
	client *connect.Client
}

func (c *resourcesClient) UpdateResource(ctx context.Context, req *evidence.UpdateResourceRequest) (*evidence.ResourceSnapshot, error) {
	var res evidence.ResourceSnapshot
	if err := c.client.CallUnary(ctx, resourcesUpdateResourceSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *resourcesClient) ListGraphEdges(ctx context.Context, req *evidence.ListGraphEdgesRequest) (*evidence.ListGraphEdgesResponse, error) {
	var res evidence.ListGraphEdgesResponse
	if err := c.client.CallUnary(ctx, resourcesListGraphEdgesSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type resourcesHandler struct{ svc ResourcesHandler }

func (h resourcesHandler) updateResource(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.UpdateResourceRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.UpdateResource(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h resourcesHandler) listGraphEdges(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req evidence.ListGraphEdgesRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListGraphEdges(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
