// Copyright 2016-2025 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/evidence/evidence.proto

package evidenceconnect

import (
	evidence "confirmate.io/core/api/evidence"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourcesName is the fully-qualified name of the Resources service.
	ResourcesName = "confirmate.evidence.v1.Resources"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourcesUpdateResourceProcedure is the fully-qualified name of the Resources's UpdateResource
	// RPC.
	ResourcesUpdateResourceProcedure = "/confirmate.evidence.v1.Resources/UpdateResource"
	// ResourcesListGraphEdgesProcedure is the fully-qualified name of the Resources's ListGraphEdges
	// RPC.
	ResourcesListGraphEdgesProcedure = "/confirmate.evidence.v1.Resources/ListGraphEdges"
)

// ResourcesClient is a client for the confirmate.evidence.v1.Resources service.
type ResourcesClient interface {
	// UpdateResource updates a resource (or creates it, if it does not exist).
	// This is used to give third-party tools the possibility to add something to
	// the resource graph.
	UpdateResource(context.Context, *connect.Request[evidence.UpdateResourceRequest]) (*connect.Response[evidence.Resource], error)
	// ListGraphEdges returns the edges (relationship) between resources in our
	// resource graph.
	ListGraphEdges(context.Context, *connect.Request[evidence.ListGraphEdgesRequest]) (*connect.Response[evidence.ListGraphEdgesResponse], error)
}

// NewResourcesClient constructs a client for the confirmate.evidence.v1.Resources service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourcesClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourcesClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resourcesMethods := evidence.File_api_evidence_evidence_proto.Services().ByName("Resources").Methods()
	return &resourcesClient{
		updateResource: connect.NewClient[evidence.UpdateResourceRequest, evidence.Resource](
			httpClient,
			baseURL+ResourcesUpdateResourceProcedure,
			connect.WithSchema(resourcesMethods.ByName("UpdateResource")),
			connect.WithClientOptions(opts...),
		),
		listGraphEdges: connect.NewClient[evidence.ListGraphEdgesRequest, evidence.ListGraphEdgesResponse](
			httpClient,
			baseURL+ResourcesListGraphEdgesProcedure,
			connect.WithSchema(resourcesMethods.ByName("ListGraphEdges")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourcesClient implements ResourcesClient.
type resourcesClient struct {
	updateResource *connect.Client[evidence.UpdateResourceRequest, evidence.Resource]
	listGraphEdges *connect.Client[evidence.ListGraphEdgesRequest, evidence.ListGraphEdgesResponse]
}

// UpdateResource calls confirmate.evidence.v1.Resources.UpdateResource.
func (c *resourcesClient) UpdateResource(ctx context.Context, req *connect.Request[evidence.UpdateResourceRequest]) (*connect.Response[evidence.Resource], error) {
	return c.updateResource.CallUnary(ctx, req)
}

// ListGraphEdges calls confirmate.evidence.v1.Resources.ListGraphEdges.
func (c *resourcesClient) ListGraphEdges(ctx context.Context, req *connect.Request[evidence.ListGraphEdgesRequest]) (*connect.Response[evidence.ListGraphEdgesResponse], error) {
	return c.listGraphEdges.CallUnary(ctx, req)
}

// ResourcesHandler is an implementation of the confirmate.evidence.v1.Resources service.
type ResourcesHandler interface {
	// UpdateResource updates a resource (or creates it, if it does not exist).
	// This is used to give third-party tools the possibility to add something to
	// the resource graph.
	UpdateResource(context.Context, *connect.Request[evidence.UpdateResourceRequest]) (*connect.Response[evidence.Resource], error)
	// ListGraphEdges returns the edges (relationship) between resources in our
	// resource graph.
	ListGraphEdges(context.Context, *connect.Request[evidence.ListGraphEdgesRequest]) (*connect.Response[evidence.ListGraphEdgesResponse], error)
}

// NewResourcesHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourcesHandler(svc ResourcesHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourcesMethods := evidence.File_api_evidence_evidence_proto.Services().ByName("Resources").Methods()
	resourcesUpdateResourceHandler := connect.NewUnaryHandler(
		ResourcesUpdateResourceProcedure,
		svc.UpdateResource,
		connect.WithSchema(resourcesMethods.ByName("UpdateResource")),
		connect.WithHandlerOptions(opts...),
	)
	resourcesListGraphEdgesHandler := connect.NewUnaryHandler(
		ResourcesListGraphEdgesProcedure,
		svc.ListGraphEdges,
		connect.WithSchema(resourcesMethods.ByName("ListGraphEdges")),
		connect.WithHandlerOptions(opts...),
	)
	return "/confirmate.evidence.v1.Resources/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourcesUpdateResourceProcedure:
			resourcesUpdateResourceHandler.ServeHTTP(w, r)
		case ResourcesListGraphEdgesProcedure:
			resourcesListGraphEdgesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourcesHandler returns CodeUnimplemented from all methods.
type UnimplementedResourcesHandler struct{}

func (UnimplementedResourcesHandler) UpdateResource(context.Context, *connect.Request[evidence.UpdateResourceRequest]) (*connect.Response[evidence.Resource], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.evidence.v1.Resources.UpdateResource is not implemented"))
}

func (UnimplementedResourcesHandler) ListGraphEdges(context.Context, *connect.Request[evidence.ListGraphEdgesRequest]) (*connect.Response[evidence.ListGraphEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.evidence.v1.Resources.ListGraphEdges is not implemented"))
}
