// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/ontology/service.proto

package ontologyconnect

import (
	ontology "confirmate.io/core/api/ontology"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OntologyServiceName is the fully-qualified name of the OntologyService service.
	OntologyServiceName = "confirmate.ontology.v1.OntologyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OntologyServiceNoopProcedure is the fully-qualified name of the OntologyService's Noop RPC.
	OntologyServiceNoopProcedure = "/confirmate.ontology.v1.OntologyService/Noop"
)

// OntologyServiceClient is a client for the confirmate.ontology.v1.OntologyService service.
type OntologyServiceClient interface {
	Noop(context.Context, *connect.Request[ontology.NoopRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewOntologyServiceClient constructs a client for the confirmate.ontology.v1.OntologyService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOntologyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OntologyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ontologyServiceMethods := ontology.File_api_ontology_service_proto.Services().ByName("OntologyService").Methods()
	return &ontologyServiceClient{
		noop: connect.NewClient[ontology.NoopRequest, emptypb.Empty](
			httpClient,
			baseURL+OntologyServiceNoopProcedure,
			connect.WithSchema(ontologyServiceMethods.ByName("Noop")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ontologyServiceClient implements OntologyServiceClient.
type ontologyServiceClient struct {
	noop *connect.Client[ontology.NoopRequest, emptypb.Empty]
}

// Noop calls confirmate.ontology.v1.OntologyService.Noop.
func (c *ontologyServiceClient) Noop(ctx context.Context, req *connect.Request[ontology.NoopRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.noop.CallUnary(ctx, req)
}

// OntologyServiceHandler is an implementation of the confirmate.ontology.v1.OntologyService
// service.
type OntologyServiceHandler interface {
	Noop(context.Context, *connect.Request[ontology.NoopRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewOntologyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOntologyServiceHandler(svc OntologyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ontologyServiceMethods := ontology.File_api_ontology_service_proto.Services().ByName("OntologyService").Methods()
	ontologyServiceNoopHandler := connect.NewUnaryHandler(
		OntologyServiceNoopProcedure,
		svc.Noop,
		connect.WithSchema(ontologyServiceMethods.ByName("Noop")),
		connect.WithHandlerOptions(opts...),
	)
	return "/confirmate.ontology.v1.OntologyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OntologyServiceNoopProcedure:
			ontologyServiceNoopHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOntologyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOntologyServiceHandler struct{}

func (UnimplementedOntologyServiceHandler) Noop(context.Context, *connect.Request[ontology.NoopRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.ontology.v1.OntologyService.Noop is not implemented"))
}
