// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/orchestrator/user.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "confirmate.io/core/api/common"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Predefined roles in the system. These should align with the roles defined in the IdP
type Role int32

const (
	Role_ROLE_UNSPECIFIED                        Role = 0
	Role_ROLE_ADMIN                              Role = 1
	Role_ROLE_COMPLIANCE_MANAGER                 Role = 2
	Role_ROLE_EXPERT_COMPLIANCE_MANAGER          Role = 3
	Role_ROLE_INTERNAL_CONTROL_OWNER             Role = 4
	Role_ROLE_TECHNICAL_IMPLEMENTER              Role = 5
	Role_ROLE_AUDITOR                            Role = 6
	Role_ROLE_CHIEF_INFORMATION_SECURITY_OFFICER Role = 7
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ADMIN",
		2: "ROLE_COMPLIANCE_MANAGER",
		3: "ROLE_EXPERT_COMPLIANCE_MANAGER",
		4: "ROLE_INTERNAL_CONTROL_OWNER",
		5: "ROLE_TECHNICAL_IMPLEMENTER",
		6: "ROLE_AUDITOR",
		7: "ROLE_CHIEF_INFORMATION_SECURITY_OFFICER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":                        0,
		"ROLE_ADMIN":                              1,
		"ROLE_COMPLIANCE_MANAGER":                 2,
		"ROLE_EXPERT_COMPLIANCE_MANAGER":          3,
		"ROLE_INTERNAL_CONTROL_OWNER":             4,
		"ROLE_TECHNICAL_IMPLEMENTER":              5,
		"ROLE_AUDITOR":                            6,
		"ROLE_CHIEF_INFORMATION_SECURITY_OFFICER": 7,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

type UserPermission_Permission int32

const (
	UserPermission_PERMISSION_UNSPECIFIED UserPermission_Permission = 0
	UserPermission_PERMISSION_READER      UserPermission_Permission = 1
	UserPermission_PERMISSION_CONTRIBUTOR UserPermission_Permission = 2
	UserPermission_PERMISSION_ADMIN       UserPermission_Permission = 3
)

// Enum value maps for UserPermission_Permission.
var (
	UserPermission_Permission_name = map[int32]string{
		0: "PERMISSION_UNSPECIFIED",
		1: "PERMISSION_READER",
		2: "PERMISSION_CONTRIBUTOR",
		3: "PERMISSION_ADMIN",
	}
	UserPermission_Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED": 0,
		"PERMISSION_READER":      1,
		"PERMISSION_CONTRIBUTOR": 2,
		"PERMISSION_ADMIN":       3,
	}
)

func (x UserPermission_Permission) Enum() *UserPermission_Permission {
	p := new(UserPermission_Permission)
	*p = x
	return p
}

func (x UserPermission_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserPermission_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[1].Descriptor()
}

func (UserPermission_Permission) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[1]
}

func (x UserPermission_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserPermission_Permission.Descriptor instead.
func (UserPermission_Permission) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{1, 0}
}

type UserPermission_ResourceType int32

const (
	UserPermission_RESOURCE_TYPE_UNSPECIFIED          UserPermission_ResourceType = 0
	UserPermission_RESOURCE_TYPE_TOE                  UserPermission_ResourceType = 1
	UserPermission_RESOURCE_TYPE_ASSESSMENT_RESULT    UserPermission_ResourceType = 2
	UserPermission_RESOURCE_TYPE_CATALOG              UserPermission_ResourceType = 3
	UserPermission_RESOURCE_TYPE_AUDIT_SCOPE          UserPermission_ResourceType = 4
	UserPermission_RESOURCE_TYPE_CERTIFICATE          UserPermission_ResourceType = 5
	UserPermission_RESOURCE_TYPE_EVIDENCE             UserPermission_ResourceType = 6
	UserPermission_RESOURCE_TYPE_USER                 UserPermission_ResourceType = 7
	UserPermission_RESOURCE_TYPE_METRIC_CONFIGURATION UserPermission_ResourceType = 8
)

// Enum value maps for UserPermission_ResourceType.
var (
	UserPermission_ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_TOE",
		2: "RESOURCE_TYPE_ASSESSMENT_RESULT",
		3: "RESOURCE_TYPE_CATALOG",
		4: "RESOURCE_TYPE_AUDIT_SCOPE",
		5: "RESOURCE_TYPE_CERTIFICATE",
		6: "RESOURCE_TYPE_EVIDENCE",
		7: "RESOURCE_TYPE_USER",
		8: "RESOURCE_TYPE_METRIC_CONFIGURATION",
	}
	UserPermission_ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED":          0,
		"RESOURCE_TYPE_TOE":                  1,
		"RESOURCE_TYPE_ASSESSMENT_RESULT":    2,
		"RESOURCE_TYPE_CATALOG":              3,
		"RESOURCE_TYPE_AUDIT_SCOPE":          4,
		"RESOURCE_TYPE_CERTIFICATE":          5,
		"RESOURCE_TYPE_EVIDENCE":             6,
		"RESOURCE_TYPE_USER":                 7,
		"RESOURCE_TYPE_METRIC_CONFIGURATION": 8,
	}
)

func (x UserPermission_ResourceType) Enum() *UserPermission_ResourceType {
	p := new(UserPermission_ResourceType)
	*p = x
	return p
}

func (x UserPermission_ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserPermission_ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[2].Descriptor()
}

func (UserPermission_ResourceType) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[2]
}

func (x UserPermission_ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserPermission_ResourceType.Descriptor instead.
func (UserPermission_ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{1, 1}
}

// Represents a user from the IdP
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the unique identifier of the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Username is the name used to be displayed
	Username *string `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// Email is the email address of the user, if available.
	Email *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// FirstName is the first name of the user, if available.
	FirstName *string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	// LastName is the last name of the user, if available.
	LastName *string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	// Roles represent the roles assigned to the user in the system, which determine their permissions and access levels.
	Roles []Role `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=confirmate.orchestrator.v1.Role" json:"roles,omitempty" gorm:"serializer:json"`
	// Enabled indicates whether the user is active/enabled in the system
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Attributes contains additional key-value pairs associated with the user, such as department or team.
	Attributes map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"serializer:json"`
	// Expiration date indicates when the user's access expires.
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	// LastAccess indicates the last time the user accessed the system.
	LastAccess    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_access,json=lastAccess,proto3" json:"last_access,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *User) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *User) GetLastAccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccess
	}
	return nil
}

type UserPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID is required to identify the user for whom the perission is being upserted.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" gorm:"column:user_id;primaryKey"`
	// Resource ID is required to identify the resource for which the permission is being upserted (e.g., ToE, Assessment Result, Catalog).
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty" gorm:"column:resource_id;primaryKey;index"`
	// Resource type is required to specify the type of the resource for which the permission is being upserted (e.g., ToE, Assessment Result, Catalog).
	ResourceType UserPermission_ResourceType `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=confirmate.orchestrator.v1.UserPermission_ResourceType" json:"resource_type,omitempty" gorm:"column:resource_type;primaryKey"`
	// Role permission is required to specify the level of access the user should have for the resource (e.g., reader, contributor, admin).
	Permission    UserPermission_Permission `protobuf:"varint,4,opt,name=permission,proto3,enum=confirmate.orchestrator.v1.UserPermission_Permission" json:"permission,omitempty" gorm:"column:permission;type:integer;not null"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermission) Reset() {
	*x = UserPermission{}
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermission) ProtoMessage() {}

func (x *UserPermission) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermission.ProtoReflect.Descriptor instead.
func (*UserPermission) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserPermission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPermission) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UserPermission) GetResourceType() UserPermission_ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return UserPermission_RESOURCE_TYPE_UNSPECIFIED
}

func (x *UserPermission) GetPermission() UserPermission_Permission {
	if x != nil {
		return x.Permission
	}
	return UserPermission_PERMISSION_UNSPECIFIED
}

var File_api_orchestrator_user_proto protoreflect.FileDescriptor

const file_api_orchestrator_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/orchestrator/user.proto\x12\x1aconfirmate.orchestrator.v1\x1a\x18api/common/runtime.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xea\x05\n" +
	"\x04User\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x02R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x03R\blastName\x88\x01\x01\x12`\n" +
	"\x05roles\x18\x06 \x03(\x0e2 .confirmate.orchestrator.v1.RoleB(\xbaH\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\x05roles\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12m\n" +
	"\n" +
	"attributes\x18\b \x03(\v20.confirmate.orchestrator.v1.User.AttributesEntryB\x1b\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\n" +
	"attributes\x12v\n" +
	"\x0fexpiration_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\x0eexpirationDate\x12n\n" +
	"\vlast_access\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\n" +
	"lastAccess\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"\xf9\x06\n" +
	"\x0eUserPermission\x12G\n" +
	"\auser_id\x18\x01 \x01(\tB.\xe0A\x02\xbaH\x03\xc8\x01\x01\x9a\x84\x9e\x03 gorm:\"column:user_id;primaryKey\"R\x06userId\x12[\n" +
	"\vresource_id\x18\x02 \x01(\tB:\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03*gorm:\"column:resource_id;primaryKey;index\"R\n" +
	"resourceId\x12\x94\x01\n" +
	"\rresource_type\x18\x03 \x01(\x0e27.confirmate.orchestrator.v1.UserPermission.ResourceTypeB6\xe0A\x02\xbaH\x05\x82\x01\x02\x10\x01\x9a\x84\x9e\x03&gorm:\"column:resource_type;primaryKey\"R\fresourceType\x12\x95\x01\n" +
	"\n" +
	"permission\x18\x04 \x01(\x0e25.confirmate.orchestrator.v1.UserPermission.PermissionB>\xe0A\x02\xbaH\x05\x82\x01\x02\x10\x01\x9a\x84\x9e\x03.gorm:\"column:permission;type:integer;not null\"R\n" +
	"permission\"q\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PERMISSION_READER\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_CONTRIBUTOR\x10\x02\x12\x14\n" +
	"\x10PERMISSION_ADMIN\x10\x03\"\x9e\x02\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESOURCE_TYPE_TOE\x10\x01\x12#\n" +
	"\x1fRESOURCE_TYPE_ASSESSMENT_RESULT\x10\x02\x12\x19\n" +
	"\x15RESOURCE_TYPE_CATALOG\x10\x03\x12\x1d\n" +
	"\x19RESOURCE_TYPE_AUDIT_SCOPE\x10\x04\x12\x1d\n" +
	"\x19RESOURCE_TYPE_CERTIFICATE\x10\x05\x12\x1a\n" +
	"\x16RESOURCE_TYPE_EVIDENCE\x10\x06\x12\x16\n" +
	"\x12RESOURCE_TYPE_USER\x10\a\x12&\n" +
	"\"RESOURCE_TYPE_METRIC_CONFIGURATION\x10\b*\xed\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x1b\n" +
	"\x17ROLE_COMPLIANCE_MANAGER\x10\x02\x12\"\n" +
	"\x1eROLE_EXPERT_COMPLIANCE_MANAGER\x10\x03\x12\x1f\n" +
	"\x1bROLE_INTERNAL_CONTROL_OWNER\x10\x04\x12\x1e\n" +
	"\x1aROLE_TECHNICAL_IMPLEMENTER\x10\x05\x12\x10\n" +
	"\fROLE_AUDITOR\x10\x06\x12+\n" +
	"'ROLE_CHIEF_INFORMATION_SECURITY_OFFICER\x10\aB%Z#confirmate.io/core/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_user_proto_rawDescOnce sync.Once
	file_api_orchestrator_user_proto_rawDescData []byte
)

func file_api_orchestrator_user_proto_rawDescGZIP() []byte {
	file_api_orchestrator_user_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)))
	})
	return file_api_orchestrator_user_proto_rawDescData
}

var file_api_orchestrator_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_orchestrator_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_orchestrator_user_proto_goTypes = []any{
	(Role)(0),                        // 0: confirmate.orchestrator.v1.Role
	(UserPermission_Permission)(0),   // 1: confirmate.orchestrator.v1.UserPermission.Permission
	(UserPermission_ResourceType)(0), // 2: confirmate.orchestrator.v1.UserPermission.ResourceType
	(*User)(nil),                     // 3: confirmate.orchestrator.v1.User
	(*UserPermission)(nil),           // 4: confirmate.orchestrator.v1.UserPermission
	nil,                              // 5: confirmate.orchestrator.v1.User.AttributesEntry
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_api_orchestrator_user_proto_depIdxs = []int32{
	0, // 0: confirmate.orchestrator.v1.User.roles:type_name -> confirmate.orchestrator.v1.Role
	5, // 1: confirmate.orchestrator.v1.User.attributes:type_name -> confirmate.orchestrator.v1.User.AttributesEntry
	6, // 2: confirmate.orchestrator.v1.User.expiration_date:type_name -> google.protobuf.Timestamp
	6, // 3: confirmate.orchestrator.v1.User.last_access:type_name -> google.protobuf.Timestamp
	2, // 4: confirmate.orchestrator.v1.UserPermission.resource_type:type_name -> confirmate.orchestrator.v1.UserPermission.ResourceType
	1, // 5: confirmate.orchestrator.v1.UserPermission.permission:type_name -> confirmate.orchestrator.v1.UserPermission.Permission
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_orchestrator_user_proto_init() }
func file_api_orchestrator_user_proto_init() {
	if File_api_orchestrator_user_proto != nil {
		return
	}
	file_api_orchestrator_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_orchestrator_user_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_user_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_user_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_user_proto_msgTypes,
	}.Build()
	File_api_orchestrator_user_proto = out.File
	file_api_orchestrator_user_proto_goTypes = nil
	file_api_orchestrator_user_proto_depIdxs = nil
}
