// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/orchestrator/user.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "confirmate.io/core/api/common"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Predefined roles in the system. These should align with the roles defined in the IdP
type Role int32

const (
	Role_ROLE_UNSPECIFIED                        Role = 0
	Role_ROLE_ADMIN                              Role = 1
	Role_ROLE_COMPLIANCE_MANAGER                 Role = 2
	Role_ROLE_EXPERT_COMPLIANCE_MANAGER          Role = 3
	Role_ROLE_INTERNAL_CONTROL_OWNER             Role = 4
	Role_ROLE_TECHNICAL_IMPLEMENTER              Role = 5
	Role_ROLE_AUDITOR                            Role = 6
	Role_ROLE_CHIEF_INFORMATION_SECURITY_OFFICER Role = 7
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ADMIN",
		2: "ROLE_COMPLIANCE_MANAGER",
		3: "ROLE_EXPERT_COMPLIANCE_MANAGER",
		4: "ROLE_INTERNAL_CONTROL_OWNER",
		5: "ROLE_TECHNICAL_IMPLEMENTER",
		6: "ROLE_AUDITOR",
		7: "ROLE_CHIEF_INFORMATION_SECURITY_OFFICER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":                        0,
		"ROLE_ADMIN":                              1,
		"ROLE_COMPLIANCE_MANAGER":                 2,
		"ROLE_EXPERT_COMPLIANCE_MANAGER":          3,
		"ROLE_INTERNAL_CONTROL_OWNER":             4,
		"ROLE_TECHNICAL_IMPLEMENTER":              5,
		"ROLE_AUDITOR":                            6,
		"ROLE_CHIEF_INFORMATION_SECURITY_OFFICER": 7,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

// Represents a user from the IdP
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the unique identifier of the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Username is the name used to be displayed
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Email is the email address of the user, if available.
	Email *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// FirstName is the first name of the user, if available.
	FirstName *string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	// LastName is the last name of the user, if available.
	LastName *string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	// Roles represent the roles assigned to the user in the system, which determine their permissions and access levels.
	Roles []Role `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=confirmate.orchestrator.v1.Role" json:"roles,omitempty" gorm:"serializer:json"`
	// Enabled indicates whether the user is active/enabled in the system
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Attributes contains additional key-value pairs associated with the user, such as department or team.
	Attributes map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"serializer:json"`
	// Expiration date indicates when the user's access expires.
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *User) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

var File_api_orchestrator_user_proto protoreflect.FileDescriptor

const file_api_orchestrator_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/orchestrator/user.proto\x12\x1aconfirmate.orchestrator.v1\x1a\x18api/common/runtime.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xf4\x04\n" +
	"\x04User\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12&\n" +
	"\busername\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\busername\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x02R\blastName\x88\x01\x01\x12`\n" +
	"\x05roles\x18\x06 \x03(\x0e2 .confirmate.orchestrator.v1.RoleB(\xbaH\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\x05roles\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12m\n" +
	"\n" +
	"attributes\x18\b \x03(\v20.confirmate.orchestrator.v1.User.AttributesEntryB\x1b\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\n" +
	"attributes\x12v\n" +
	"\x0fexpiration_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\x0eexpirationDate\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_emailB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name*\xed\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x1b\n" +
	"\x17ROLE_COMPLIANCE_MANAGER\x10\x02\x12\"\n" +
	"\x1eROLE_EXPERT_COMPLIANCE_MANAGER\x10\x03\x12\x1f\n" +
	"\x1bROLE_INTERNAL_CONTROL_OWNER\x10\x04\x12\x1e\n" +
	"\x1aROLE_TECHNICAL_IMPLEMENTER\x10\x05\x12\x10\n" +
	"\fROLE_AUDITOR\x10\x06\x12+\n" +
	"'ROLE_CHIEF_INFORMATION_SECURITY_OFFICER\x10\aB%Z#confirmate.io/core/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_user_proto_rawDescOnce sync.Once
	file_api_orchestrator_user_proto_rawDescData []byte
)

func file_api_orchestrator_user_proto_rawDescGZIP() []byte {
	file_api_orchestrator_user_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)))
	})
	return file_api_orchestrator_user_proto_rawDescData
}

var file_api_orchestrator_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orchestrator_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_orchestrator_user_proto_goTypes = []any{
	(Role)(0),                     // 0: confirmate.orchestrator.v1.Role
	(*User)(nil),                  // 1: confirmate.orchestrator.v1.User
	nil,                           // 2: confirmate.orchestrator.v1.User.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_orchestrator_user_proto_depIdxs = []int32{
	0, // 0: confirmate.orchestrator.v1.User.roles:type_name -> confirmate.orchestrator.v1.Role
	2, // 1: confirmate.orchestrator.v1.User.attributes:type_name -> confirmate.orchestrator.v1.User.AttributesEntry
	3, // 2: confirmate.orchestrator.v1.User.expiration_date:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_orchestrator_user_proto_init() }
func file_api_orchestrator_user_proto_init() {
	if File_api_orchestrator_user_proto != nil {
		return
	}
	file_api_orchestrator_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_orchestrator_user_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_user_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_user_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_user_proto_msgTypes,
	}.Build()
	File_api_orchestrator_user_proto = out.File
	file_api_orchestrator_user_proto_goTypes = nil
	file_api_orchestrator_user_proto_depIdxs = nil
}
