// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/orchestrator/user.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "confirmate.io/core/api/common"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Predefined roles in the system. These should align with the roles defined in the IdP
type Role int32

const (
	Role_ROLE_ADMIN                              Role = 0
	Role_ROLE_COMPLIANCE_MANAGER                 Role = 1
	Role_ROLE_EXPERT_COMPLIANCE_MANAGER          Role = 2
	Role_ROLE_INTERNAL_CONTROL_OWNER             Role = 3
	Role_ROLE_TECHNICAL_IMPLEMENTER              Role = 4
	Role_ROLE_AUDITOR                            Role = 5
	Role_ROLE_CHIEF_INFORMATION_SECURITY_OFFICER Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_ADMIN",
		1: "ROLE_COMPLIANCE_MANAGER",
		2: "ROLE_EXPERT_COMPLIANCE_MANAGER",
		3: "ROLE_INTERNAL_CONTROL_OWNER",
		4: "ROLE_TECHNICAL_IMPLEMENTER",
		5: "ROLE_AUDITOR",
		6: "ROLE_CHIEF_INFORMATION_SECURITY_OFFICER",
	}
	Role_value = map[string]int32{
		"ROLE_ADMIN":                              0,
		"ROLE_COMPLIANCE_MANAGER":                 1,
		"ROLE_EXPERT_COMPLIANCE_MANAGER":          2,
		"ROLE_INTERNAL_CONTROL_OWNER":             3,
		"ROLE_TECHNICAL_IMPLEMENTER":              4,
		"ROLE_AUDITOR":                            5,
		"ROLE_CHIEF_INFORMATION_SECURITY_OFFICER": 6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

// Represents a user from the IdP
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the unique identifier of the user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Username is the name used to be displayed
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Email is the email address of the user, if available.
	Email *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// FirstName is the first name of the user, if available.
	FirstName *string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	// LastName is the last name of the user, if available.
	LastName *string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	// Roles represent the roles assigned to the user in the system, which determine their permissions and access levels.
	Roles []Role `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=confirmate.orchestrator.v1.Role" json:"roles,omitempty" gorm:"serializer:json"`
	// Enabled indicates whether the user is active/enabled in the system
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Attributes contains additional key-value pairs associated with the user, such as department or team.
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"serializer:json"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{1}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListUsersRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	PageSize      int32                    `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                   `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                   `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                     `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetFilter() *ListUsersRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListUsersRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_orchestrator_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRolesRequest) Reset() {
	*x = ListUserRolesRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRolesRequest) ProtoMessage() {}

func (x *ListUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRolesRequest.ProtoReflect.Descriptor instead.
func (*ListUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []Role                 `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=confirmate.orchestrator.v1.Role" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRolesResponse) Reset() {
	*x = ListUserRolesResponse{}
	mi := &file_api_orchestrator_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRolesResponse) ProtoMessage() {}

func (x *ListUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRolesResponse.ProtoReflect.Descriptor instead.
func (*ListUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserRolesResponse) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUsersRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Filter by role (e.g., "compliance_manager")
	Role *Role `protobuf:"varint,1,opt,name=role,proto3,enum=confirmate.orchestrator.v1.Role,oneof" json:"role,omitempty"`
	// Optional. Filter by enabled/disabled status
	Enabled *bool `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// Optional. Search query for username, email, first name, or last name
	Search *string `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	// Optional. Filter by specific attribute key-value pairs (e.g., department)
	Attributes    map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest_Filter) Reset() {
	*x = ListUsersRequest_Filter{}
	mi := &file_api_orchestrator_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest_Filter) ProtoMessage() {}

func (x *ListUsersRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListUsersRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListUsersRequest_Filter) GetRole() Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return Role_ROLE_ADMIN
}

func (x *ListUsersRequest_Filter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListUsersRequest_Filter) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListUsersRequest_Filter) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_api_orchestrator_user_proto protoreflect.FileDescriptor

const file_api_orchestrator_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/orchestrator/user.proto\x12\x1aconfirmate.orchestrator.v1\x1a\x18api/common/runtime.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\xfc\x03\n" +
	"\x04User\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12&\n" +
	"\busername\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\busername\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x02R\blastName\x88\x01\x01\x12`\n" +
	"\x05roles\x18\x06 \x03(\x0e2 .confirmate.orchestrator.v1.RoleB(\xbaH\n" +
	"\x92\x01\a\"\x05\x82\x01\x02\x10\x01\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\x05roles\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12m\n" +
	"\n" +
	"attributes\x18\b \x03(\v20.confirmate.orchestrator.v1.User.AttributesEntryB\x1b\x9a\x84\x9e\x03\x16gorm:\"serializer:json\"R\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_emailB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"\x17\n" +
	"\x15GetCurrentUserRequest\"5\n" +
	"\x0eGetUserRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x06userId\"\xa8\x04\n" +
	"\x10ListUsersRequest\x12P\n" +
	"\x06filter\x18\x01 \x01(\v23.confirmate.orchestrator.v1.ListUsersRequest.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03asc\x1a\xcd\x02\n" +
	"\x06Filter\x12C\n" +
	"\x04role\x18\x01 \x01(\x0e2 .confirmate.orchestrator.v1.RoleB\b\xbaH\x05\x82\x01\x02\x10\x01H\x00R\x04role\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x01R\aenabled\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x02R\x06search\x88\x01\x01\x12c\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2C.confirmate.orchestrator.v1.ListUsersRequest.Filter.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_roleB\n" +
	"\n" +
	"\b_enabledB\t\n" +
	"\a_searchB\t\n" +
	"\a_filter\"s\n" +
	"\x11ListUsersResponse\x126\n" +
	"\x05users\x18\x01 \x03(\v2 .confirmate.orchestrator.v1.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"R\n" +
	"\x14ListUserRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"O\n" +
	"\x15ListUserRolesResponse\x126\n" +
	"\x05roles\x18\x01 \x03(\x0e2 .confirmate.orchestrator.v1.RoleR\x05roles*\xd7\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x00\x12\x1b\n" +
	"\x17ROLE_COMPLIANCE_MANAGER\x10\x01\x12\"\n" +
	"\x1eROLE_EXPERT_COMPLIANCE_MANAGER\x10\x02\x12\x1f\n" +
	"\x1bROLE_INTERNAL_CONTROL_OWNER\x10\x03\x12\x1e\n" +
	"\x1aROLE_TECHNICAL_IMPLEMENTER\x10\x04\x12\x10\n" +
	"\fROLE_AUDITOR\x10\x05\x12+\n" +
	"'ROLE_CHIEF_INFORMATION_SECURITY_OFFICER\x10\x062\xc7\x04\n" +
	"\x0eUserManagement\x12\x88\x01\n" +
	"\x0eGetCurrentUser\x121.confirmate.orchestrator.v1.GetCurrentUserRequest\x1a .confirmate.orchestrator.v1.User\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/orchestrator/users/me\x12\x88\x01\n" +
	"\tListUsers\x12,.confirmate.orchestrator.v1.ListUsersRequest\x1a-.confirmate.orchestrator.v1.ListUsersResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/orchestrator/users\x12\x81\x01\n" +
	"\aGetUser\x12*.confirmate.orchestrator.v1.GetUserRequest\x1a .confirmate.orchestrator.v1.User\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/orchestrator/users/{user_id}\x12\x9a\x01\n" +
	"\rListUserRoles\x120.confirmate.orchestrator.v1.ListUserRolesRequest\x1a1.confirmate.orchestrator.v1.ListUserRolesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/orchestrator/users/rolesB%Z#confirmate.io/core/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_user_proto_rawDescOnce sync.Once
	file_api_orchestrator_user_proto_rawDescData []byte
)

func file_api_orchestrator_user_proto_rawDescGZIP() []byte {
	file_api_orchestrator_user_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)))
	})
	return file_api_orchestrator_user_proto_rawDescData
}

var file_api_orchestrator_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orchestrator_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_orchestrator_user_proto_goTypes = []any{
	(Role)(0),                       // 0: confirmate.orchestrator.v1.Role
	(*User)(nil),                    // 1: confirmate.orchestrator.v1.User
	(*GetCurrentUserRequest)(nil),   // 2: confirmate.orchestrator.v1.GetCurrentUserRequest
	(*GetUserRequest)(nil),          // 3: confirmate.orchestrator.v1.GetUserRequest
	(*ListUsersRequest)(nil),        // 4: confirmate.orchestrator.v1.ListUsersRequest
	(*ListUsersResponse)(nil),       // 5: confirmate.orchestrator.v1.ListUsersResponse
	(*ListUserRolesRequest)(nil),    // 6: confirmate.orchestrator.v1.ListUserRolesRequest
	(*ListUserRolesResponse)(nil),   // 7: confirmate.orchestrator.v1.ListUserRolesResponse
	nil,                             // 8: confirmate.orchestrator.v1.User.AttributesEntry
	(*ListUsersRequest_Filter)(nil), // 9: confirmate.orchestrator.v1.ListUsersRequest.Filter
	nil,                             // 10: confirmate.orchestrator.v1.ListUsersRequest.Filter.AttributesEntry
}
var file_api_orchestrator_user_proto_depIdxs = []int32{
	0,  // 0: confirmate.orchestrator.v1.User.roles:type_name -> confirmate.orchestrator.v1.Role
	8,  // 1: confirmate.orchestrator.v1.User.attributes:type_name -> confirmate.orchestrator.v1.User.AttributesEntry
	9,  // 2: confirmate.orchestrator.v1.ListUsersRequest.filter:type_name -> confirmate.orchestrator.v1.ListUsersRequest.Filter
	1,  // 3: confirmate.orchestrator.v1.ListUsersResponse.users:type_name -> confirmate.orchestrator.v1.User
	0,  // 4: confirmate.orchestrator.v1.ListUserRolesResponse.roles:type_name -> confirmate.orchestrator.v1.Role
	0,  // 5: confirmate.orchestrator.v1.ListUsersRequest.Filter.role:type_name -> confirmate.orchestrator.v1.Role
	10, // 6: confirmate.orchestrator.v1.ListUsersRequest.Filter.attributes:type_name -> confirmate.orchestrator.v1.ListUsersRequest.Filter.AttributesEntry
	2,  // 7: confirmate.orchestrator.v1.UserManagement.GetCurrentUser:input_type -> confirmate.orchestrator.v1.GetCurrentUserRequest
	4,  // 8: confirmate.orchestrator.v1.UserManagement.ListUsers:input_type -> confirmate.orchestrator.v1.ListUsersRequest
	3,  // 9: confirmate.orchestrator.v1.UserManagement.GetUser:input_type -> confirmate.orchestrator.v1.GetUserRequest
	6,  // 10: confirmate.orchestrator.v1.UserManagement.ListUserRoles:input_type -> confirmate.orchestrator.v1.ListUserRolesRequest
	1,  // 11: confirmate.orchestrator.v1.UserManagement.GetCurrentUser:output_type -> confirmate.orchestrator.v1.User
	5,  // 12: confirmate.orchestrator.v1.UserManagement.ListUsers:output_type -> confirmate.orchestrator.v1.ListUsersResponse
	1,  // 13: confirmate.orchestrator.v1.UserManagement.GetUser:output_type -> confirmate.orchestrator.v1.User
	7,  // 14: confirmate.orchestrator.v1.UserManagement.ListUserRoles:output_type -> confirmate.orchestrator.v1.ListUserRolesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_orchestrator_user_proto_init() }
func file_api_orchestrator_user_proto_init() {
	if File_api_orchestrator_user_proto != nil {
		return
	}
	file_api_orchestrator_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_orchestrator_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_orchestrator_user_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orchestrator_user_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_user_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_user_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_user_proto_msgTypes,
	}.Build()
	File_api_orchestrator_user_proto = out.File
	file_api_orchestrator_user_proto_goTypes = nil
	file_api_orchestrator_user_proto_depIdxs = nil
}
