// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/orchestrator/workflow.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlImplementationState represents the lifecycle state of a control implementation.
type ControlImplementationState int32

const (
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED    ControlImplementationState = 0
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_OPEN           ControlImplementationState = 1
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_IN_PROGRESS    ControlImplementationState = 2
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_IMPLEMENTED    ControlImplementationState = 3
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_READY_FOR_REVIEW ControlImplementationState = 4
	ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_ACCEPTED       ControlImplementationState = 5
)

// Enum value maps for ControlImplementationState.
var (
	ControlImplementationState_name = map[int32]string{
		0: "CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED",
		1: "CONTROL_IMPLEMENTATION_STATE_OPEN",
		2: "CONTROL_IMPLEMENTATION_STATE_IN_PROGRESS",
		3: "CONTROL_IMPLEMENTATION_STATE_IMPLEMENTED",
		4: "CONTROL_IMPLEMENTATION_STATE_READY_FOR_REVIEW",
		5: "CONTROL_IMPLEMENTATION_STATE_ACCEPTED",
	}
	ControlImplementationState_value = map[string]int32{
		"CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED":    0,
		"CONTROL_IMPLEMENTATION_STATE_OPEN":           1,
		"CONTROL_IMPLEMENTATION_STATE_IN_PROGRESS":    2,
		"CONTROL_IMPLEMENTATION_STATE_IMPLEMENTED":    3,
		"CONTROL_IMPLEMENTATION_STATE_READY_FOR_REVIEW": 4,
		"CONTROL_IMPLEMENTATION_STATE_ACCEPTED":       5,
	}
)

func (x ControlImplementationState) Enum() *ControlImplementationState {
	p := new(ControlImplementationState)
	*p = x
	return p
}

func (x ControlImplementationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlImplementationState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_workflow_proto_enumTypes[0].Descriptor()
}

func (ControlImplementationState) Type() protoreflect.EnumType {
	return &file_api_orchestrator_workflow_proto_enumTypes[0]
}

func (x ControlImplementationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlImplementationState.Descriptor instead.
func (ControlImplementationState) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{0}
}

// ControlImplementation tracks the implementation status of a specific control within an audit
// scope. There is exactly one ControlImplementation per (audit scope, control) pair.
type ControlImplementation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	// The audit scope this implementation belongs to.
	AuditScopeId string `protobuf:"bytes,2,opt,name=audit_scope_id,json=auditScopeId,proto3" json:"audit_scope_id,omitempty"`
	// Denormalized from the audit scope for efficient authorization checks.
	TargetOfEvaluationId string `protobuf:"bytes,3,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3" json:"target_of_evaluation_id,omitempty"`
	// Control composite key — mirrors Control's primary key.
	ControlId                string `protobuf:"bytes,4,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	ControlCategoryName      string `protobuf:"bytes,5,opt,name=control_category_name,json=controlCategoryName,proto3" json:"control_category_name,omitempty"`
	ControlCategoryCatalogId string `protobuf:"bytes,6,opt,name=control_category_catalog_id,json=controlCategoryCatalogId,proto3" json:"control_category_catalog_id,omitempty"`
	// Current implementation state.
	State ControlImplementationState `protobuf:"varint,7,opt,name=state,proto3,enum=confirmate.orchestrator.v1.ControlImplementationState" json:"state,omitempty"`
	// The user (identified by User.id) responsible for implementing this control.
	AssigneeId *string                `protobuf:"bytes,8,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	// Full history of state transitions (populated on read).
	Transitions   []*ControlImplementationTransition `protobuf:"bytes,11,rep,name=transitions,proto3" json:"transitions,omitempty" gorm:"foreignKey:ControlImplementationId;constraint:OnDelete:CASCADE"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlImplementation) Reset() {
	*x = ControlImplementation{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlImplementation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlImplementation) ProtoMessage() {}

func (x *ControlImplementation) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlImplementation.ProtoReflect.Descriptor instead.
func (*ControlImplementation) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *ControlImplementation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlImplementation) GetAuditScopeId() string {
	if x != nil {
		return x.AuditScopeId
	}
	return ""
}

func (x *ControlImplementation) GetTargetOfEvaluationId() string {
	if x != nil {
		return x.TargetOfEvaluationId
	}
	return ""
}

func (x *ControlImplementation) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ControlImplementation) GetControlCategoryName() string {
	if x != nil {
		return x.ControlCategoryName
	}
	return ""
}

func (x *ControlImplementation) GetControlCategoryCatalogId() string {
	if x != nil {
		return x.ControlCategoryCatalogId
	}
	return ""
}

func (x *ControlImplementation) GetState() ControlImplementationState {
	if x != nil {
		return x.State
	}
	return ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED
}

func (x *ControlImplementation) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *ControlImplementation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ControlImplementation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ControlImplementation) GetTransitions() []*ControlImplementationTransition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

// ControlImplementationTransition records a single state change in a ControlImplementation's
// lifecycle, capturing who made the change and when.
type ControlImplementationTransition struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	Id                      string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	ControlImplementationId string                     `protobuf:"bytes,2,opt,name=control_implementation_id,json=controlImplementationId,proto3" json:"control_implementation_id,omitempty"`
	FromState               ControlImplementationState `protobuf:"varint,3,opt,name=from_state,json=fromState,proto3,enum=confirmate.orchestrator.v1.ControlImplementationState" json:"from_state,omitempty"`
	ToState                 ControlImplementationState `protobuf:"varint,4,opt,name=to_state,json=toState,proto3,enum=confirmate.orchestrator.v1.ControlImplementationState" json:"to_state,omitempty"`
	// User.id of the person who triggered this transition.
	PerformedBy   string                 `protobuf:"bytes,5,opt,name=performed_by,json=performedBy,proto3" json:"performed_by,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty" gorm:"serializer:timestamppb;type:timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlImplementationTransition) Reset() {
	*x = ControlImplementationTransition{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlImplementationTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlImplementationTransition) ProtoMessage() {}

func (x *ControlImplementationTransition) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlImplementationTransition.ProtoReflect.Descriptor instead.
func (*ControlImplementationTransition) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *ControlImplementationTransition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlImplementationTransition) GetControlImplementationId() string {
	if x != nil {
		return x.ControlImplementationId
	}
	return ""
}

func (x *ControlImplementationTransition) GetFromState() ControlImplementationState {
	if x != nil {
		return x.FromState
	}
	return ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED
}

func (x *ControlImplementationTransition) GetToState() ControlImplementationState {
	if x != nil {
		return x.ToState
	}
	return ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED
}

func (x *ControlImplementationTransition) GetPerformedBy() string {
	if x != nil {
		return x.PerformedBy
	}
	return ""
}

func (x *ControlImplementationTransition) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type CreateControlImplementationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ControlImplementation *ControlImplementation `protobuf:"bytes,1,opt,name=control_implementation,json=controlImplementation,proto3" json:"control_implementation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateControlImplementationRequest) Reset() {
	*x = CreateControlImplementationRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateControlImplementationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateControlImplementationRequest) ProtoMessage() {}

func (x *CreateControlImplementationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateControlImplementationRequest.ProtoReflect.Descriptor instead.
func (*CreateControlImplementationRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *CreateControlImplementationRequest) GetControlImplementation() *ControlImplementation {
	if x != nil {
		return x.ControlImplementation
	}
	return nil
}

type GetControlImplementationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlImplementationRequest) Reset() {
	*x = GetControlImplementationRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlImplementationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlImplementationRequest) ProtoMessage() {}

func (x *GetControlImplementationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlImplementationRequest.ProtoReflect.Descriptor instead.
func (*GetControlImplementationRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GetControlImplementationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListControlImplementationsRequest struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Filter        *ListControlImplementationsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	PageSize      int32                                     `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                                    `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                                    `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                                      `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListControlImplementationsRequest) Reset() {
	*x = ListControlImplementationsRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlImplementationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlImplementationsRequest) ProtoMessage() {}

func (x *ListControlImplementationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlImplementationsRequest.ProtoReflect.Descriptor instead.
func (*ListControlImplementationsRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ListControlImplementationsRequest) GetFilter() *ListControlImplementationsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListControlImplementationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListControlImplementationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListControlImplementationsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListControlImplementationsRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListControlImplementationsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	ControlImplementations []*ControlImplementation `protobuf:"bytes,1,rep,name=control_implementations,json=controlImplementations,proto3" json:"control_implementations,omitempty"`
	NextPageToken          string                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListControlImplementationsResponse) Reset() {
	*x = ListControlImplementationsResponse{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlImplementationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlImplementationsResponse) ProtoMessage() {}

func (x *ListControlImplementationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlImplementationsResponse.ProtoReflect.Descriptor instead.
func (*ListControlImplementationsResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListControlImplementationsResponse) GetControlImplementations() []*ControlImplementation {
	if x != nil {
		return x.ControlImplementations
	}
	return nil
}

func (x *ListControlImplementationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateControlImplementationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ControlImplementation *ControlImplementation `protobuf:"bytes,1,opt,name=control_implementation,json=controlImplementation,proto3" json:"control_implementation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateControlImplementationRequest) Reset() {
	*x = UpdateControlImplementationRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateControlImplementationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateControlImplementationRequest) ProtoMessage() {}

func (x *UpdateControlImplementationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateControlImplementationRequest.ProtoReflect.Descriptor instead.
func (*UpdateControlImplementationRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateControlImplementationRequest) GetControlImplementation() *ControlImplementation {
	if x != nil {
		return x.ControlImplementation
	}
	return nil
}

type TransitionControlImplementationStateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToState       ControlImplementationState `protobuf:"varint,2,opt,name=to_state,json=toState,proto3,enum=confirmate.orchestrator.v1.ControlImplementationState" json:"to_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionControlImplementationStateRequest) Reset() {
	*x = TransitionControlImplementationStateRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionControlImplementationStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionControlImplementationStateRequest) ProtoMessage() {}

func (x *TransitionControlImplementationStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionControlImplementationStateRequest.ProtoReflect.Descriptor instead.
func (*TransitionControlImplementationStateRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *TransitionControlImplementationStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransitionControlImplementationStateRequest) GetToState() ControlImplementationState {
	if x != nil {
		return x.ToState
	}
	return ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED
}

type RemoveControlImplementationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveControlImplementationRequest) Reset() {
	*x = RemoveControlImplementationRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveControlImplementationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveControlImplementationRequest) ProtoMessage() {}

func (x *RemoveControlImplementationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveControlImplementationRequest.ProtoReflect.Descriptor instead.
func (*RemoveControlImplementationRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveControlImplementationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListControlImplementationsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Filter by audit scope.
	AuditScopeId *string `protobuf:"bytes,1,opt,name=audit_scope_id,json=auditScopeId,proto3,oneof" json:"audit_scope_id,omitempty"`
	// Optional. Filter by current state.
	State *ControlImplementationState `protobuf:"varint,2,opt,name=state,proto3,enum=confirmate.orchestrator.v1.ControlImplementationState,oneof" json:"state,omitempty"`
	// Optional. Filter by assignee.
	AssigneeId    *string `protobuf:"bytes,3,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListControlImplementationsRequest_Filter) Reset() {
	*x = ListControlImplementationsRequest_Filter{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlImplementationsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlImplementationsRequest_Filter) ProtoMessage() {}

func (x *ListControlImplementationsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlImplementationsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListControlImplementationsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListControlImplementationsRequest_Filter) GetAuditScopeId() string {
	if x != nil && x.AuditScopeId != nil {
		return *x.AuditScopeId
	}
	return ""
}

func (x *ListControlImplementationsRequest_Filter) GetState() ControlImplementationState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ControlImplementationState_CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED
}

func (x *ListControlImplementationsRequest_Filter) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

var File_api_orchestrator_workflow_proto protoreflect.FileDescriptor

const file_api_orchestrator_workflow_proto_rawDesc = "" +
	"\n\x1fapi/orchestrator/workflow.proto\x12\x1aconfirmate.orchestrator.v1\x1a\x1bbuf/validate/validate" +
	".proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/t" +
	"agger.proto\"\x83\x07\n\x15ControlImplementation\x121\n\x02id\x18\x01 \x01(\tB!\xe0A\x02\xbaH\x05r" +
	"\x03\xb0\x01\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x02id\x121\n\x0eaudit_scope_id\x18\x02 \x01" +
	"(\tB\x0b\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x0cauditScopeId\x12B\n\x17target_of_evaluation_id\x18" +
	"\x03 \x01(\tB\x0b\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x14targetOfEvaluationId\x12)\n\ncontrol_id\x18" +
	"\x04 \x01(\tB\n\xe0A\x02\xbaH\x04r\x02\x10\x01R\tcontrolId\x12>\n\x15control_category_name\x18\x05 " +
	"\x01(\tB\n\xe0A\x02\xbaH\x04r\x02\x10\x01R\x13controlCategoryName\x12I\n\x1bcontrol_category_catalog" +
	"_id\x18\x06 \x01(\tB\n\xe0A\x02\xbaH\x04r\x02\x10\x01R\x18controlCategoryCatalogId\x12L\n\x05state" +
	"\x18\x07 \x01(\x0e26.confirmate.orchestrator.v1.ControlImplementationStateR\x05state\x12$\n\x0bassig" +
	"nee_id\x18\x08 \x01(\tH\x00R\nassigneeId\x88\x01\x01\x12l\n\ncreated_at\x18\t \x01(\x0b2\x1a.google." +
	"protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\tcreatedAt\x12l" +
	"\n\nupdated_at\x18\n \x01(\x0b2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:ti" +
	"mestamppb;type:timestamp\"R\tupdatedAt\x12\xa9\x01\n\x0btransitions\x18\x0b \x03(\x0b2;.confirmate.o" +
	"rchestrator.v1.ControlImplementationTransitionBJ\x9a\x84\x9e\x03Egorm:\"foreignKey:ControlImplementa" +
	"tionId;constraint:OnDelete:CASCADE\"R\x0btransitionsB\x0e\n\x0c_assignee_id\"\xd2\x03\n\x1fControlIm" +
	"plementationTransition\x121\n\x02id\x18\x01 \x01(\tB!\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e" +
	"\x03\x11gorm:\"primaryKey\"R\x02id\x12G\n\x19control_implementation_id\x18\x02 \x01(\tB\x0b\xe0A\x02" +
	"\xbaH\x05r\x03\xb0\x01\x01R\x17controlImplementationId\x12U\n\nfrom_state\x18\x03 \x01(\x0e26.confir" +
	"mate.orchestrator.v1.ControlImplementationStateR\tfromState\x12V\n\x08to_state\x18\x04 \x01(\x0e26.c" +
	"onfirmate.orchestrator.v1.ControlImplementationStateB\x03\xe0A\x02R\x07toState\x12!\n\x0cperformed_b" +
	"y\x18\x05 \x01(\tR\x0bperformedBy\x12a\n\x04time\x18\x06 \x01(\x0b2\x1a.google.protobuf.TimestampB1" +
	"\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\x04time\"\x99\x01\n\"CreateControlI" +
	"mplementationRequest\x12s\n\x16control_implementation\x18\x01 \x01(\x0b21.confirmate.orchestrator.v1" +
	".ControlImplementationB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x15controlImplementation\">\n\x1fGetControl" +
	"ImplementationRequest\x12\x1b\n\x02id\x18\x01 \x01(\tB\x0b\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id" +
	"\"\xea\x03\n!ListControlImplementationsRequest\x12a\n\x06filter\x18\x01 \x01(\x0b2D.confirmate.orche" +
	"strator.v1.ListControlImplementationsRequest.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n\tpage_size" +
	"\x18\n \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x0b \x01(\tR\tpageToken\x12\x19\n\x08order_b" +
	"y\x18\x0c \x01(\tR\x07orderBy\x12\x10\n\x03asc\x18\x0d \x01(\x08R\x03asc\x1a\xed\x01\n\x06Filter\x12" +
	"3\n\x0eaudit_scope_id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01H\x00R\x0cauditScopeId\x88\x01" +
	"\x01\x12[\n\x05state\x18\x02 \x01(\x0e26.confirmate.orchestrator.v1.ControlImplementationStateB\x08" +
	"\xbaH\x05\x82\x01\x02\x10\x01H\x01R\x05state\x88\x01\x01\x12$\n\x0bassignee_id\x18\x03 \x01(\tH\x02R" +
	"\nassigneeId\x88\x01\x01B\x11\n\x0f_audit_scope_idB\x08\n\x06_stateB\x0e\n\x0c_assignee_idB\t\n\x07_" +
	"filter\"\xb8\x01\n\"ListControlImplementationsResponse\x12j\n\x17control_implementations\x18\x01 " +
	"\x03(\x0b21.confirmate.orchestrator.v1.ControlImplementationR\x16controlImplementations\x12&\n\x0fne" +
	"xt_page_token\x18\x02 \x01(\tR\x0dnextPageToken\"\x99\x01\n\"UpdateControlImplementationRequest\x12s" +
	"\n\x16control_implementation\x18\x01 \x01(\x0b21.confirmate.orchestrator.v1.ControlImplementationB\t" +
	"\xe0A\x02\xbaH\x03\xc8\x01\x01R\x15controlImplementation\"\xac\x01\n+TransitionControlImplementation" +
	"StateRequest\x12\x1b\n\x02id\x18\x01 \x01(\tB\x0b\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12`\n" +
	"\x08to_state\x18\x02 \x01(\x0e26.confirmate.orchestrator.v1.ControlImplementationStateB\x0d\xe0A\x02" +
	"\xbaH\x07\x82\x01\x04\x10\x01 \x00R\x07toState\"A\n\"RemoveControlImplementationRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\x0b\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id*\xab\x02\n\x1aControlImplement" +
	"ationState\x12,\n(CONTROL_IMPLEMENTATION_STATE_UNSPECIFIED\x10\x00\x12%\n!CONTROL_IMPLEMENTATION_STA" +
	"TE_OPEN\x10\x01\x12,\n(CONTROL_IMPLEMENTATION_STATE_IN_PROGRESS\x10\x02\x12,\n(CONTROL_IMPLEMENTATIO" +
	"N_STATE_IMPLEMENTED\x10\x03\x121\n-CONTROL_IMPLEMENTATION_STATE_READY_FOR_REVIEW\x10" +
	"\x04\x12)\n%CONTROL_IMPLEMENTATION_STATE_ACCEPTED\x10\x05B%Z#confirmate.io/core/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_workflow_proto_rawDescOnce sync.Once
	file_api_orchestrator_workflow_proto_rawDescData []byte
)

func file_api_orchestrator_workflow_proto_rawDescGZIP() []byte {
	file_api_orchestrator_workflow_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_workflow_proto_rawDesc), len(file_api_orchestrator_workflow_proto_rawDesc)))
	})
	return file_api_orchestrator_workflow_proto_rawDescData
}

var file_api_orchestrator_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orchestrator_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_orchestrator_workflow_proto_goTypes = []any{
	(ControlImplementationState)(0),                     // 0: confirmate.orchestrator.v1.ControlImplementationState
	(*ControlImplementation)(nil),                       // 1: confirmate.orchestrator.v1.ControlImplementation
	(*ControlImplementationTransition)(nil),             // 2: confirmate.orchestrator.v1.ControlImplementationTransition
	(*CreateControlImplementationRequest)(nil),          // 3: confirmate.orchestrator.v1.CreateControlImplementationRequest
	(*GetControlImplementationRequest)(nil),             // 4: confirmate.orchestrator.v1.GetControlImplementationRequest
	(*ListControlImplementationsRequest)(nil),           // 5: confirmate.orchestrator.v1.ListControlImplementationsRequest
	(*ListControlImplementationsResponse)(nil),          // 6: confirmate.orchestrator.v1.ListControlImplementationsResponse
	(*UpdateControlImplementationRequest)(nil),          // 7: confirmate.orchestrator.v1.UpdateControlImplementationRequest
	(*TransitionControlImplementationStateRequest)(nil), // 8: confirmate.orchestrator.v1.TransitionControlImplementationStateRequest
	(*RemoveControlImplementationRequest)(nil),          // 9: confirmate.orchestrator.v1.RemoveControlImplementationRequest
	(*ListControlImplementationsRequest_Filter)(nil),    // 10: confirmate.orchestrator.v1.ListControlImplementationsRequest.Filter
	(*timestamppb.Timestamp)(nil),                       // 11: google.protobuf.Timestamp
}
var file_api_orchestrator_workflow_proto_depIdxs = []int32{
	0,  // 0: confirmate.orchestrator.v1.ControlImplementation.state:type_name -> confirmate.orchestrator.v1.ControlImplementationState
	11, // 1: confirmate.orchestrator.v1.ControlImplementation.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: confirmate.orchestrator.v1.ControlImplementation.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: confirmate.orchestrator.v1.ControlImplementation.transitions:type_name -> confirmate.orchestrator.v1.ControlImplementationTransition
	0,  // 4: confirmate.orchestrator.v1.ControlImplementationTransition.from_state:type_name -> confirmate.orchestrator.v1.ControlImplementationState
	0,  // 5: confirmate.orchestrator.v1.ControlImplementationTransition.to_state:type_name -> confirmate.orchestrator.v1.ControlImplementationState
	11, // 6: confirmate.orchestrator.v1.ControlImplementationTransition.time:type_name -> google.protobuf.Timestamp
	1,  // 7: confirmate.orchestrator.v1.CreateControlImplementationRequest.control_implementation:type_name -> confirmate.orchestrator.v1.ControlImplementation
	10, // 8: confirmate.orchestrator.v1.ListControlImplementationsRequest.filter:type_name -> confirmate.orchestrator.v1.ListControlImplementationsRequest.Filter
	1,  // 9: confirmate.orchestrator.v1.ListControlImplementationsResponse.control_implementations:type_name -> confirmate.orchestrator.v1.ControlImplementation
	1,  // 10: confirmate.orchestrator.v1.UpdateControlImplementationRequest.control_implementation:type_name -> confirmate.orchestrator.v1.ControlImplementation
	0,  // 11: confirmate.orchestrator.v1.TransitionControlImplementationStateRequest.to_state:type_name -> confirmate.orchestrator.v1.ControlImplementationState
	0,  // 12: confirmate.orchestrator.v1.ListControlImplementationsRequest.Filter.state:type_name -> confirmate.orchestrator.v1.ControlImplementationState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_orchestrator_workflow_proto_init() }
func file_api_orchestrator_workflow_proto_init() {
	if File_api_orchestrator_workflow_proto != nil {
		return
	}
	file_api_orchestrator_workflow_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_workflow_proto_rawDesc), len(file_api_orchestrator_workflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_orchestrator_workflow_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_workflow_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_workflow_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_workflow_proto_msgTypes,
	}.Build()
	File_api_orchestrator_workflow_proto = out.File
	file_api_orchestrator_workflow_proto_goTypes = nil
	file_api_orchestrator_workflow_proto_depIdxs = nil
}
