// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/orchestrator/workflow.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlInScopeState represents the lifecycle state of a control's implementation within an audit scope.
type ControlInScopeState int32

const (
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED      ControlInScopeState = 0
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_OPEN             ControlInScopeState = 1
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_IN_PROGRESS      ControlInScopeState = 2
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_IMPLEMENTED      ControlInScopeState = 3
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_READY_FOR_REVIEW ControlInScopeState = 4
	ControlInScopeState_CONTROL_IN_SCOPE_STATE_ACCEPTED         ControlInScopeState = 5
)

// Enum value maps for ControlInScopeState.
var (
	ControlInScopeState_name = map[int32]string{
		0: "CONTROL_IN_SCOPE_STATE_UNSPECIFIED",
		1: "CONTROL_IN_SCOPE_STATE_OPEN",
		2: "CONTROL_IN_SCOPE_STATE_IN_PROGRESS",
		3: "CONTROL_IN_SCOPE_STATE_IMPLEMENTED",
		4: "CONTROL_IN_SCOPE_STATE_READY_FOR_REVIEW",
		5: "CONTROL_IN_SCOPE_STATE_ACCEPTED",
	}
	ControlInScopeState_value = map[string]int32{
		"CONTROL_IN_SCOPE_STATE_UNSPECIFIED":      0,
		"CONTROL_IN_SCOPE_STATE_OPEN":             1,
		"CONTROL_IN_SCOPE_STATE_IN_PROGRESS":      2,
		"CONTROL_IN_SCOPE_STATE_IMPLEMENTED":      3,
		"CONTROL_IN_SCOPE_STATE_READY_FOR_REVIEW": 4,
		"CONTROL_IN_SCOPE_STATE_ACCEPTED":         5,
	}
)

func (x ControlInScopeState) Enum() *ControlInScopeState {
	p := new(ControlInScopeState)
	*p = x
	return p
}

func (x ControlInScopeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlInScopeState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_workflow_proto_enumTypes[0].Descriptor()
}

func (ControlInScopeState) Type() protoreflect.EnumType {
	return &file_api_orchestrator_workflow_proto_enumTypes[0]
}

func (x ControlInScopeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlInScopeState.Descriptor instead.
func (ControlInScopeState) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{0}
}

// ControlInScope tracks the implementation status of a specific control within an audit scope.
// There is exactly one ControlInScope per (audit scope, control) pair. Records are auto-created
// when an audit scope is created and can also be managed manually via the CreateControlInScope /
// RemoveControlInScope RPCs.
type ControlInScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// AuditScopeId describes the audit scope this record belongs to.
	AuditScopeId string `protobuf:"bytes,2,opt,name=audit_scope_id,json=auditScopeId,proto3" json:"audit_scope_id,omitempty"`
	// TargetOfEvaluationId is denormalized from the audit scope for efficient authorization checks.
	// It is set server-side and not required in requests.
	TargetOfEvaluationId string `protobuf:"bytes,3,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3" json:"target_of_evaluation_id,omitempty"`
	// ControlId references the control being implemented (unique UUID since #270).
	ControlId string `protobuf:"bytes,4,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	// Current implementation state.
	State ControlInScopeState `protobuf:"varint,5,opt,name=state,proto3,enum=confirmate.orchestrator.v1.ControlInScopeState" json:"state,omitempty"`
	// ImplementationDetails contains free-form notes about how the control is being addressed.
	ImplementationDetails *string `protobuf:"bytes,6,opt,name=implementation_details,json=implementationDetails,proto3,oneof" json:"implementation_details,omitempty"`
	// AssigneeId is the ID of the orchestrator User entity responsible for implementing this control.
	// This is the User.id of the person assigned, not the actor making the request.
	AssigneeId    *string                `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlInScope) Reset() {
	*x = ControlInScope{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlInScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlInScope) ProtoMessage() {}

func (x *ControlInScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlInScope.ProtoReflect.Descriptor instead.
func (*ControlInScope) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *ControlInScope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlInScope) GetAuditScopeId() string {
	if x != nil {
		return x.AuditScopeId
	}
	return ""
}

func (x *ControlInScope) GetTargetOfEvaluationId() string {
	if x != nil {
		return x.TargetOfEvaluationId
	}
	return ""
}

func (x *ControlInScope) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ControlInScope) GetState() ControlInScopeState {
	if x != nil {
		return x.State
	}
	return ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED
}

func (x *ControlInScope) GetImplementationDetails() string {
	if x != nil && x.ImplementationDetails != nil {
		return *x.ImplementationDetails
	}
	return ""
}

func (x *ControlInScope) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *ControlInScope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ControlInScope) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AuditTrailEvent is a persisted record of any significant change related to an audit scope,
// such as a control being scoped/unscoped or an audit scope state transition. The event_data
// field holds a typed payload (one of the event messages below) serialized as JSON via anypb.
type AuditTrailEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// AuditScopeId is the primary resource this event belongs to.
	AuditScopeId string `protobuf:"bytes,2,opt,name=audit_scope_id,json=auditScopeId,proto3" json:"audit_scope_id,omitempty"`
	// ActorId is the User.id of the person who triggered this event.
	ActorId string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Comment provides optional context for the event.
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	// Time is the creation time of this event.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// EventData holds the typed event payload serialized as JSON.
	EventData *anypb.Any `protobuf:"bytes,6,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	// ControlInScopeId optionally links this event to the affected ControlInScope record.
	// Not set for events where the ControlInScope record is deleted (e.g. RemoveControlInScope).
	ControlInScopeId *string `protobuf:"bytes,7,opt,name=control_in_scope_id,json=controlInScopeId,proto3,oneof" json:"control_in_scope_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditTrailEvent) Reset() {
	*x = AuditTrailEvent{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditTrailEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditTrailEvent) ProtoMessage() {}

func (x *AuditTrailEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditTrailEvent.ProtoReflect.Descriptor instead.
func (*AuditTrailEvent) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *AuditTrailEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditTrailEvent) GetAuditScopeId() string {
	if x != nil {
		return x.AuditScopeId
	}
	return ""
}

func (x *AuditTrailEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditTrailEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AuditTrailEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditTrailEvent) GetEventData() *anypb.Any {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *AuditTrailEvent) GetControlInScopeId() string {
	if x != nil && x.ControlInScopeId != nil {
		return *x.ControlInScopeId
	}
	return ""
}

// ControlScopingEvent is emitted when a control is brought in or out of scope.
// control_in_scope_id is only set for in-scope events; it is omitted for out-of-scope events
// because the ControlInScope record is deleted as part of the same transaction.
type ControlScopingEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ControlInScopeId string                 `protobuf:"bytes,1,opt,name=control_in_scope_id,json=controlInScopeId,proto3" json:"control_in_scope_id,omitempty"`
	ControlId        string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	AuditScopeId     string                 `protobuf:"bytes,3,opt,name=audit_scope_id,json=auditScopeId,proto3" json:"audit_scope_id,omitempty"`
	InScope          bool                   `protobuf:"varint,4,opt,name=in_scope,json=inScope,proto3" json:"in_scope,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ControlScopingEvent) Reset() {
	*x = ControlScopingEvent{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlScopingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlScopingEvent) ProtoMessage() {}

func (x *ControlScopingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlScopingEvent.ProtoReflect.Descriptor instead.
func (*ControlScopingEvent) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *ControlScopingEvent) GetControlInScopeId() string {
	if x != nil {
		return x.ControlInScopeId
	}
	return ""
}

func (x *ControlScopingEvent) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ControlScopingEvent) GetAuditScopeId() string {
	if x != nil {
		return x.AuditScopeId
	}
	return ""
}

func (x *ControlScopingEvent) GetInScope() bool {
	if x != nil {
		return x.InScope
	}
	return false
}

// ControlInScopeTransitionEvent is emitted when a ControlInScope moves between implementation states.
type ControlInScopeTransitionEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ControlInScopeId string                 `protobuf:"bytes,1,opt,name=control_in_scope_id,json=controlInScopeId,proto3" json:"control_in_scope_id,omitempty"`
	FromState        ControlInScopeState    `protobuf:"varint,2,opt,name=from_state,json=fromState,proto3,enum=confirmate.orchestrator.v1.ControlInScopeState" json:"from_state,omitempty"`
	ToState          ControlInScopeState    `protobuf:"varint,3,opt,name=to_state,json=toState,proto3,enum=confirmate.orchestrator.v1.ControlInScopeState" json:"to_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ControlInScopeTransitionEvent) Reset() {
	*x = ControlInScopeTransitionEvent{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlInScopeTransitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlInScopeTransitionEvent) ProtoMessage() {}

func (x *ControlInScopeTransitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlInScopeTransitionEvent.ProtoReflect.Descriptor instead.
func (*ControlInScopeTransitionEvent) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ControlInScopeTransitionEvent) GetControlInScopeId() string {
	if x != nil {
		return x.ControlInScopeId
	}
	return ""
}

func (x *ControlInScopeTransitionEvent) GetFromState() ControlInScopeState {
	if x != nil {
		return x.FromState
	}
	return ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED
}

func (x *ControlInScopeTransitionEvent) GetToState() ControlInScopeState {
	if x != nil {
		return x.ToState
	}
	return ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED
}

type CreateControlInScopeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AuditScopeId string                 `protobuf:"bytes,1,opt,name=audit_scope_id,json=auditScopeId,proto3" json:"audit_scope_id,omitempty"`
	ControlId    string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	// TargetOfEvaluationId must match the target_of_evaluation_id of the referenced audit scope.
	// It is required here so the server can avoid a round-trip fetch of the AuditScope.
	TargetOfEvaluationId string `protobuf:"bytes,4,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3" json:"target_of_evaluation_id,omitempty"`
	// AssigneeId is the ID of the orchestrator User entity initially responsible for this control.
	AssigneeId    *string `protobuf:"bytes,3,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateControlInScopeRequest) Reset() {
	*x = CreateControlInScopeRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateControlInScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateControlInScopeRequest) ProtoMessage() {}

func (x *CreateControlInScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateControlInScopeRequest.ProtoReflect.Descriptor instead.
func (*CreateControlInScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *CreateControlInScopeRequest) GetAuditScopeId() string {
	if x != nil {
		return x.AuditScopeId
	}
	return ""
}

func (x *CreateControlInScopeRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *CreateControlInScopeRequest) GetTargetOfEvaluationId() string {
	if x != nil {
		return x.TargetOfEvaluationId
	}
	return ""
}

func (x *CreateControlInScopeRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

type GetControlInScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlInScopeRequest) Reset() {
	*x = GetControlInScopeRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlInScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlInScopeRequest) ProtoMessage() {}

func (x *GetControlInScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlInScopeRequest.ProtoReflect.Descriptor instead.
func (*GetControlInScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *GetControlInScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListControlsInScopeRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Filter        *ListControlsInScopeRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	PageSize      int32                              `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                             `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                             `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                               `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListControlsInScopeRequest) Reset() {
	*x = ListControlsInScopeRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlsInScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlsInScopeRequest) ProtoMessage() {}

func (x *ListControlsInScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlsInScopeRequest.ProtoReflect.Descriptor instead.
func (*ListControlsInScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *ListControlsInScopeRequest) GetFilter() *ListControlsInScopeRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListControlsInScopeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListControlsInScopeRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListControlsInScopeRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListControlsInScopeRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListControlsInScopeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ControlsInScope []*ControlInScope      `protobuf:"bytes,1,rep,name=controls_in_scope,json=controlsInScope,proto3" json:"controls_in_scope,omitempty"`
	NextPageToken   string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListControlsInScopeResponse) Reset() {
	*x = ListControlsInScopeResponse{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlsInScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlsInScopeResponse) ProtoMessage() {}

func (x *ListControlsInScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlsInScopeResponse.ProtoReflect.Descriptor instead.
func (*ListControlsInScopeResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *ListControlsInScopeResponse) GetControlsInScope() []*ControlInScope {
	if x != nil {
		return x.ControlsInScope
	}
	return nil
}

func (x *ListControlsInScopeResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateControlInScopeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssigneeId *string                `protobuf:"bytes,2,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	// ImplementationDetails contains free-form notes about how the control is being addressed.
	ImplementationDetails *string `protobuf:"bytes,3,opt,name=implementation_details,json=implementationDetails,proto3,oneof" json:"implementation_details,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateControlInScopeRequest) Reset() {
	*x = UpdateControlInScopeRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateControlInScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateControlInScopeRequest) ProtoMessage() {}

func (x *UpdateControlInScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateControlInScopeRequest.ProtoReflect.Descriptor instead.
func (*UpdateControlInScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateControlInScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateControlInScopeRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *UpdateControlInScopeRequest) GetImplementationDetails() string {
	if x != nil && x.ImplementationDetails != nil {
		return *x.ImplementationDetails
	}
	return ""
}

type TransitionControlInScopeStateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToState ControlInScopeState    `protobuf:"varint,2,opt,name=to_state,json=toState,proto3,enum=confirmate.orchestrator.v1.ControlInScopeState" json:"to_state,omitempty"`
	// Comment explaining the reason for this transition.
	Comment       string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionControlInScopeStateRequest) Reset() {
	*x = TransitionControlInScopeStateRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionControlInScopeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionControlInScopeStateRequest) ProtoMessage() {}

func (x *TransitionControlInScopeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionControlInScopeStateRequest.ProtoReflect.Descriptor instead.
func (*TransitionControlInScopeStateRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *TransitionControlInScopeStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransitionControlInScopeStateRequest) GetToState() ControlInScopeState {
	if x != nil {
		return x.ToState
	}
	return ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED
}

func (x *TransitionControlInScopeStateRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RemoveControlInScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveControlInScopeRequest) Reset() {
	*x = RemoveControlInScopeRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveControlInScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveControlInScopeRequest) ProtoMessage() {}

func (x *RemoveControlInScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveControlInScopeRequest.ProtoReflect.Descriptor instead.
func (*RemoveControlInScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveControlInScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAuditTrailEventsRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Filter        *ListAuditTrailEventsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	PageSize      int32                               `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                              `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                              `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                                `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditTrailEventsRequest) Reset() {
	*x = ListAuditTrailEventsRequest{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditTrailEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditTrailEventsRequest) ProtoMessage() {}

func (x *ListAuditTrailEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditTrailEventsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditTrailEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *ListAuditTrailEventsRequest) GetFilter() *ListAuditTrailEventsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListAuditTrailEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditTrailEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditTrailEventsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListAuditTrailEventsRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListAuditTrailEventsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuditTrailEvents []*AuditTrailEvent     `protobuf:"bytes,1,rep,name=audit_trail_events,json=auditTrailEvents,proto3" json:"audit_trail_events,omitempty"`
	NextPageToken    string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAuditTrailEventsResponse) Reset() {
	*x = ListAuditTrailEventsResponse{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditTrailEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditTrailEventsResponse) ProtoMessage() {}

func (x *ListAuditTrailEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditTrailEventsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditTrailEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *ListAuditTrailEventsResponse) GetAuditTrailEvents() []*AuditTrailEvent {
	if x != nil {
		return x.AuditTrailEvents
	}
	return nil
}

func (x *ListAuditTrailEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListControlsInScopeRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Filter by audit scope.
	AuditScopeId *string `protobuf:"bytes,1,opt,name=audit_scope_id,json=auditScopeId,proto3,oneof" json:"audit_scope_id,omitempty"`
	// Optional. Filter by current state.
	State *ControlInScopeState `protobuf:"varint,2,opt,name=state,proto3,enum=confirmate.orchestrator.v1.ControlInScopeState,oneof" json:"state,omitempty"`
	// Optional. Filter by assignee.
	AssigneeId    *string `protobuf:"bytes,3,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListControlsInScopeRequest_Filter) Reset() {
	*x = ListControlsInScopeRequest_Filter{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListControlsInScopeRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListControlsInScopeRequest_Filter) ProtoMessage() {}

func (x *ListControlsInScopeRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListControlsInScopeRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListControlsInScopeRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListControlsInScopeRequest_Filter) GetAuditScopeId() string {
	if x != nil && x.AuditScopeId != nil {
		return *x.AuditScopeId
	}
	return ""
}

func (x *ListControlsInScopeRequest_Filter) GetState() ControlInScopeState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ControlInScopeState_CONTROL_IN_SCOPE_STATE_UNSPECIFIED
}

func (x *ListControlsInScopeRequest_Filter) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

type ListAuditTrailEventsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Filter by audit scope.
	AuditScopeId *string `protobuf:"bytes,1,opt,name=audit_scope_id,json=auditScopeId,proto3,oneof" json:"audit_scope_id,omitempty"`
	// Optional. Filter by control in scope (returns only events for that specific record).
	ControlInScopeId *string `protobuf:"bytes,2,opt,name=control_in_scope_id,json=controlInScopeId,proto3,oneof" json:"control_in_scope_id,omitempty"`
	// Optional. Filter by the actor (User.id) who triggered the events.
	ActorId       *string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditTrailEventsRequest_Filter) Reset() {
	*x = ListAuditTrailEventsRequest_Filter{}
	mi := &file_api_orchestrator_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditTrailEventsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditTrailEventsRequest_Filter) ProtoMessage() {}

func (x *ListAuditTrailEventsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditTrailEventsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAuditTrailEventsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_workflow_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListAuditTrailEventsRequest_Filter) GetAuditScopeId() string {
	if x != nil && x.AuditScopeId != nil {
		return *x.AuditScopeId
	}
	return ""
}

func (x *ListAuditTrailEventsRequest_Filter) GetControlInScopeId() string {
	if x != nil && x.ControlInScopeId != nil {
		return *x.ControlInScopeId
	}
	return ""
}

func (x *ListAuditTrailEventsRequest_Filter) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

var File_api_orchestrator_workflow_proto protoreflect.FileDescriptor

const file_api_orchestrator_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/orchestrator/workflow.proto\x12\x1aconfirmate.orchestrator.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tagger/tagger.proto\"\x89\x06\n" +
	"\x0eControlInScope\x121\n" +
	"\x02id\x18\x01 \x01(\tB!\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x02id\x12q\n" +
	"\x0eaudit_scope_id\x18\x02 \x01(\tBK\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03;gorm:\"uniqueIndex:idx_control_in_scope_audit_scope_control\"R\fauditScopeId\x125\n" +
	"\x17target_of_evaluation_id\x18\x03 \x01(\tR\x14targetOfEvaluationId\x12j\n" +
	"\n" +
	"control_id\x18\x04 \x01(\tBK\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03;gorm:\"uniqueIndex:idx_control_in_scope_audit_scope_control\"R\tcontrolId\x12E\n" +
	"\x05state\x18\x05 \x01(\x0e2/.confirmate.orchestrator.v1.ControlInScopeStateR\x05state\x12:\n" +
	"\x16implementation_details\x18\x06 \x01(\tH\x00R\x15implementationDetails\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\a \x01(\tH\x01R\n" +
	"assigneeId\x88\x01\x01\x12l\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\tcreatedAt\x12l\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB1\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\tupdatedAtB\x19\n" +
	"\x17_implementation_detailsB\x0e\n" +
	"\f_assignee_id\"\xea\x03\n" +
	"\x0fAuditTrailEvent\x121\n" +
	"\x02id\x18\x01 \x01(\tB!\xe0A\x03\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x02id\x12:\n" +
	"\x0eaudit_scope_id\x18\x02 \x01(\tB\x14\xe0A\x03\x9a\x84\x9e\x03\fgorm:\"index\"R\fauditScopeId\x12\x1e\n" +
	"\bactor_id\x18\x03 \x01(\tB\x03\xe0A\x03R\aactorId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12o\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB4\xe0A\x03\x9a\x84\x9e\x03,gorm:\"serializer:timestamppb;type:timestamp\"R\tcreatedAt\x12^\n" +
	"\n" +
	"event_data\x18\x06 \x01(\v2\x14.google.protobuf.AnyB)\xe0A\x03\x9a\x84\x9e\x03!gorm:\"serializer:anypb;type:text\"R\teventData\x12E\n" +
	"\x13control_in_scope_id\x18\a \x01(\tB\x11\x9a\x84\x9e\x03\fgorm:\"index\"H\x00R\x10controlInScopeId\x88\x01\x01B\x16\n" +
	"\x14_control_in_scope_id\"\xa4\x01\n" +
	"\x13ControlScopingEvent\x12-\n" +
	"\x13control_in_scope_id\x18\x01 \x01(\tR\x10controlInScopeId\x12\x1d\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\tcontrolId\x12$\n" +
	"\x0eaudit_scope_id\x18\x03 \x01(\tR\fauditScopeId\x12\x19\n" +
	"\bin_scope\x18\x04 \x01(\bR\ainScope\"\xea\x01\n" +
	"\x1dControlInScopeTransitionEvent\x12-\n" +
	"\x13control_in_scope_id\x18\x01 \x01(\tR\x10controlInScopeId\x12N\n" +
	"\n" +
	"from_state\x18\x02 \x01(\x0e2/.confirmate.orchestrator.v1.ControlInScopeStateR\tfromState\x12J\n" +
	"\bto_state\x18\x03 \x01(\x0e2/.confirmate.orchestrator.v1.ControlInScopeStateR\atoState\"\xf6\x01\n" +
	"\x1bCreateControlInScopeRequest\x121\n" +
	"\x0eaudit_scope_id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\fauditScopeId\x12*\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\tcontrolId\x12B\n" +
	"\x17target_of_evaluation_id\x18\x04 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x14targetOfEvaluationId\x12$\n" +
	"\vassignee_id\x18\x03 \x01(\tH\x00R\n" +
	"assigneeId\x88\x01\x01B\x0e\n" +
	"\f_assignee_id\"7\n" +
	"\x18GetControlInScopeRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\xd5\x03\n" +
	"\x1aListControlsInScopeRequest\x12Z\n" +
	"\x06filter\x18\x01 \x01(\v2=.confirmate.orchestrator.v1.ListControlsInScopeRequest.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03asc\x1a\xe6\x01\n" +
	"\x06Filter\x123\n" +
	"\x0eaudit_scope_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\fauditScopeId\x88\x01\x01\x12T\n" +
	"\x05state\x18\x02 \x01(\x0e2/.confirmate.orchestrator.v1.ControlInScopeStateB\b\xbaH\x05\x82\x01\x02\x10\x01H\x01R\x05state\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\x03 \x01(\tH\x02R\n" +
	"assigneeId\x88\x01\x01B\x11\n" +
	"\x0f_audit_scope_idB\b\n" +
	"\x06_stateB\x0e\n" +
	"\f_assignee_idB\t\n" +
	"\a_filter\"\x9d\x01\n" +
	"\x1bListControlsInScopeResponse\x12V\n" +
	"\x11controls_in_scope\x18\x01 \x03(\v2*.confirmate.orchestrator.v1.ControlInScopeR\x0fcontrolsInScope\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc7\x01\n" +
	"\x1bUpdateControlInScopeRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12$\n" +
	"\vassignee_id\x18\x02 \x01(\tH\x00R\n" +
	"assigneeId\x88\x01\x01\x12:\n" +
	"\x16implementation_details\x18\x03 \x01(\tH\x01R\x15implementationDetails\x88\x01\x01B\x0e\n" +
	"\f_assignee_idB\x19\n" +
	"\x17_implementation_details\"\xc4\x01\n" +
	"$TransitionControlInScopeStateRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12Y\n" +
	"\bto_state\x18\x02 \x01(\x0e2/.confirmate.orchestrator.v1.ControlInScopeStateB\r\xe0A\x02\xbaH\a\x82\x01\x04\x10\x01 \x00R\atoState\x12$\n" +
	"\acomment\x18\x03 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\acomment\":\n" +
	"\x1bRemoveControlInScopeRequest\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\xc4\x03\n" +
	"\x1bListAuditTrailEventsRequest\x12[\n" +
	"\x06filter\x18\x01 \x01(\v2>.confirmate.orchestrator.v1.ListAuditTrailEventsRequest.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03asc\x1a\xd3\x01\n" +
	"\x06Filter\x123\n" +
	"\x0eaudit_scope_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\fauditScopeId\x88\x01\x01\x12<\n" +
	"\x13control_in_scope_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\x10controlInScopeId\x88\x01\x01\x12\x1e\n" +
	"\bactor_id\x18\x03 \x01(\tH\x02R\aactorId\x88\x01\x01B\x11\n" +
	"\x0f_audit_scope_idB\x16\n" +
	"\x14_control_in_scope_idB\v\n" +
	"\t_actor_idB\t\n" +
	"\a_filter\"\xa1\x01\n" +
	"\x1cListAuditTrailEventsResponse\x12Y\n" +
	"\x12audit_trail_events\x18\x01 \x03(\v2+.confirmate.orchestrator.v1.AuditTrailEventR\x10auditTrailEvents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x80\x02\n" +
	"\x13ControlInScopeState\x12&\n" +
	"\"CONTROL_IN_SCOPE_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONTROL_IN_SCOPE_STATE_OPEN\x10\x01\x12&\n" +
	"\"CONTROL_IN_SCOPE_STATE_IN_PROGRESS\x10\x02\x12&\n" +
	"\"CONTROL_IN_SCOPE_STATE_IMPLEMENTED\x10\x03\x12+\n" +
	"'CONTROL_IN_SCOPE_STATE_READY_FOR_REVIEW\x10\x04\x12#\n" +
	"\x1fCONTROL_IN_SCOPE_STATE_ACCEPTED\x10\x05B%Z#confirmate.io/core/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_workflow_proto_rawDescOnce sync.Once
	file_api_orchestrator_workflow_proto_rawDescData []byte
)

func file_api_orchestrator_workflow_proto_rawDescGZIP() []byte {
	file_api_orchestrator_workflow_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_workflow_proto_rawDesc), len(file_api_orchestrator_workflow_proto_rawDesc)))
	})
	return file_api_orchestrator_workflow_proto_rawDescData
}

var file_api_orchestrator_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orchestrator_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_orchestrator_workflow_proto_goTypes = []any{
	(ControlInScopeState)(0),                     // 0: confirmate.orchestrator.v1.ControlInScopeState
	(*ControlInScope)(nil),                       // 1: confirmate.orchestrator.v1.ControlInScope
	(*AuditTrailEvent)(nil),                      // 2: confirmate.orchestrator.v1.AuditTrailEvent
	(*ControlScopingEvent)(nil),                  // 3: confirmate.orchestrator.v1.ControlScopingEvent
	(*ControlInScopeTransitionEvent)(nil),        // 4: confirmate.orchestrator.v1.ControlInScopeTransitionEvent
	(*CreateControlInScopeRequest)(nil),          // 5: confirmate.orchestrator.v1.CreateControlInScopeRequest
	(*GetControlInScopeRequest)(nil),             // 6: confirmate.orchestrator.v1.GetControlInScopeRequest
	(*ListControlsInScopeRequest)(nil),           // 7: confirmate.orchestrator.v1.ListControlsInScopeRequest
	(*ListControlsInScopeResponse)(nil),          // 8: confirmate.orchestrator.v1.ListControlsInScopeResponse
	(*UpdateControlInScopeRequest)(nil),          // 9: confirmate.orchestrator.v1.UpdateControlInScopeRequest
	(*TransitionControlInScopeStateRequest)(nil), // 10: confirmate.orchestrator.v1.TransitionControlInScopeStateRequest
	(*RemoveControlInScopeRequest)(nil),          // 11: confirmate.orchestrator.v1.RemoveControlInScopeRequest
	(*ListAuditTrailEventsRequest)(nil),          // 12: confirmate.orchestrator.v1.ListAuditTrailEventsRequest
	(*ListAuditTrailEventsResponse)(nil),         // 13: confirmate.orchestrator.v1.ListAuditTrailEventsResponse
	(*ListControlsInScopeRequest_Filter)(nil),    // 14: confirmate.orchestrator.v1.ListControlsInScopeRequest.Filter
	(*ListAuditTrailEventsRequest_Filter)(nil),   // 15: confirmate.orchestrator.v1.ListAuditTrailEventsRequest.Filter
	(*timestamppb.Timestamp)(nil),                // 16: google.protobuf.Timestamp
	(*anypb.Any)(nil),                            // 17: google.protobuf.Any
}
var file_api_orchestrator_workflow_proto_depIdxs = []int32{
	0,  // 0: confirmate.orchestrator.v1.ControlInScope.state:type_name -> confirmate.orchestrator.v1.ControlInScopeState
	16, // 1: confirmate.orchestrator.v1.ControlInScope.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: confirmate.orchestrator.v1.ControlInScope.updated_at:type_name -> google.protobuf.Timestamp
	16, // 3: confirmate.orchestrator.v1.AuditTrailEvent.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: confirmate.orchestrator.v1.AuditTrailEvent.event_data:type_name -> google.protobuf.Any
	0,  // 5: confirmate.orchestrator.v1.ControlInScopeTransitionEvent.from_state:type_name -> confirmate.orchestrator.v1.ControlInScopeState
	0,  // 6: confirmate.orchestrator.v1.ControlInScopeTransitionEvent.to_state:type_name -> confirmate.orchestrator.v1.ControlInScopeState
	14, // 7: confirmate.orchestrator.v1.ListControlsInScopeRequest.filter:type_name -> confirmate.orchestrator.v1.ListControlsInScopeRequest.Filter
	1,  // 8: confirmate.orchestrator.v1.ListControlsInScopeResponse.controls_in_scope:type_name -> confirmate.orchestrator.v1.ControlInScope
	0,  // 9: confirmate.orchestrator.v1.TransitionControlInScopeStateRequest.to_state:type_name -> confirmate.orchestrator.v1.ControlInScopeState
	15, // 10: confirmate.orchestrator.v1.ListAuditTrailEventsRequest.filter:type_name -> confirmate.orchestrator.v1.ListAuditTrailEventsRequest.Filter
	2,  // 11: confirmate.orchestrator.v1.ListAuditTrailEventsResponse.audit_trail_events:type_name -> confirmate.orchestrator.v1.AuditTrailEvent
	0,  // 12: confirmate.orchestrator.v1.ListControlsInScopeRequest.Filter.state:type_name -> confirmate.orchestrator.v1.ControlInScopeState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_orchestrator_workflow_proto_init() }
func file_api_orchestrator_workflow_proto_init() {
	if File_api_orchestrator_workflow_proto != nil {
		return
	}
	file_api_orchestrator_workflow_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_orchestrator_workflow_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_workflow_proto_rawDesc), len(file_api_orchestrator_workflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_orchestrator_workflow_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_workflow_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_workflow_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_workflow_proto_msgTypes,
	}.Build()
	File_api_orchestrator_workflow_proto = out.File
	file_api_orchestrator_workflow_proto_goTypes = nil
	file_api_orchestrator_workflow_proto_depIdxs = nil
}
