/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/assessment/evidences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Assesses the evidence sent by the discovery. Part of the public API, also
         *      exposed as REST.
         */
        post: operations["Assessment_AssessEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description AssessEvidenceResponse belongs to AssessEvidence, which uses a custom unary
         *      RPC and therefore requires a response message according to the style
         *      convention. Since no return values are required, this is empty.
         */
        AssessEvidenceResponse: {
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "ASSESSMENT_STATUS_UNSPECIFIED" | "ASSESSMENT_STATUS_WAITING_FOR_RELATED" | "ASSESSMENT_STATUS_ASSESSED" | "ASSESSMENT_STATUS_FAILED";
        };
        /** @description An evidence resource */
        Evidence: {
            /** @description the ID in a uuid format */
            id?: string;
            /**
             * Format: date-time
             * @description time of evidence creation
             */
            timestamp?: string;
            /** @description Reference to a target of evaluation (e.g., service, organization) this evidence was gathered from */
            targetOfEvaluationId?: string;
            /** @description Reference to the tool which provided the evidence */
            toolId?: string;
            /** @description Semantic representation of the Cloud resource according to our defined ontology */
            resource?: components["schemas"]["Resource"];
            /**
             * @description Very experimental property. Use at own risk. This property will be deleted again.
             *
             *      Related resource IDs. The assessment will wait until all evidences for related resource have arrived in the
             *      assessment and are recent enough. In the future, this will be replaced with information in the "related" edges in
             *      the resource. For now, this needs to be set manually in the evidence.
             */
            experimentalRelatedResourceIds?: string[];
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Resource is a wrapper around google.protobuf.Value that is needed for
         *      persistence reasons.
         */
        Resource: {
            /**
             * @description Id contains a unique ID for each resource. This is specific for the cloud
             *      provider this resource was gathered for and can for example be a resource
             *      URL.
             */
            id: string;
            /**
             * @description TargetOfEvaluationId is the UUID for the target of evaluation to which this resource
             *      belongs to.
             */
            targetOfEvaluationId: string;
            /**
             * @description ResourceType contains a comma separated string of resource types according
             *      to our ontology.
             */
            resourceType: string;
            /** @description Reference to the tool which provided the resource */
            toolId: string;
            /**
             * @description Properties contains a protobuf message that describe the resource in the
             *      terms of our ontology.
             */
            properties: components["schemas"]["GoogleProtobufAny"];
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAssessEvidenceResponse = components['schemas']['AssessEvidenceResponse'];
export type SchemaEvidence = components['schemas']['Evidence'];
export type SchemaGoogleProtobufAny = components['schemas']['GoogleProtobufAny'];
export type SchemaResource = components['schemas']['Resource'];
export type SchemaStatus = components['schemas']['Status'];
export type $defs = Record<string, never>;
export interface operations {
    Assessment_AssessEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Evidence"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessEvidenceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
