// Copyright 2026 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/orchestrator/user.proto

package orchestratorconnect

import (
	orchestrator "confirmate.io/core/api/orchestrator"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserManagementName is the fully-qualified name of the UserManagement service.
	UserManagementName = "confirmate.orchestrator.v1.UserManagement"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserManagementGetCurrentUserProcedure is the fully-qualified name of the UserManagement's
	// GetCurrentUser RPC.
	UserManagementGetCurrentUserProcedure = "/confirmate.orchestrator.v1.UserManagement/GetCurrentUser"
	// UserManagementListUsersProcedure is the fully-qualified name of the UserManagement's ListUsers
	// RPC.
	UserManagementListUsersProcedure = "/confirmate.orchestrator.v1.UserManagement/ListUsers"
	// UserManagementGetUserProcedure is the fully-qualified name of the UserManagement's GetUser RPC.
	UserManagementGetUserProcedure = "/confirmate.orchestrator.v1.UserManagement/GetUser"
	// UserManagementListUserRolesProcedure is the fully-qualified name of the UserManagement's
	// ListUserRoles RPC.
	UserManagementListUserRolesProcedure = "/confirmate.orchestrator.v1.UserManagement/ListUserRoles"
)

// UserManagementClient is a client for the confirmate.orchestrator.v1.UserManagement service.
type UserManagementClient interface {
	// Returns information about the currently authenticated user
	GetCurrentUser(context.Context, *connect.Request[orchestrator.GetCurrentUserRequest]) (*connect.Response[orchestrator.User], error)
	// Lists users with optional filtering
	ListUsers(context.Context, *connect.Request[orchestrator.ListUsersRequest]) (*connect.Response[orchestrator.ListUsersResponse], error)
	// Retrieves a specific user by their ID. This endpoint is restricted to users with elevated roles, such as admin.
	GetUser(context.Context, *connect.Request[orchestrator.GetUserRequest]) (*connect.Response[orchestrator.User], error)
	// Lists all predefined roles in the system.
	ListUserRoles(context.Context, *connect.Request[orchestrator.ListUserRolesRequest]) (*connect.Response[orchestrator.ListUserRolesResponse], error)
}

// NewUserManagementClient constructs a client for the confirmate.orchestrator.v1.UserManagement
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserManagementClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserManagementClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userManagementMethods := orchestrator.File_api_orchestrator_user_proto.Services().ByName("UserManagement").Methods()
	return &userManagementClient{
		getCurrentUser: connect.NewClient[orchestrator.GetCurrentUserRequest, orchestrator.User](
			httpClient,
			baseURL+UserManagementGetCurrentUserProcedure,
			connect.WithSchema(userManagementMethods.ByName("GetCurrentUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[orchestrator.ListUsersRequest, orchestrator.ListUsersResponse](
			httpClient,
			baseURL+UserManagementListUsersProcedure,
			connect.WithSchema(userManagementMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[orchestrator.GetUserRequest, orchestrator.User](
			httpClient,
			baseURL+UserManagementGetUserProcedure,
			connect.WithSchema(userManagementMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listUserRoles: connect.NewClient[orchestrator.ListUserRolesRequest, orchestrator.ListUserRolesResponse](
			httpClient,
			baseURL+UserManagementListUserRolesProcedure,
			connect.WithSchema(userManagementMethods.ByName("ListUserRoles")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userManagementClient implements UserManagementClient.
type userManagementClient struct {
	getCurrentUser *connect.Client[orchestrator.GetCurrentUserRequest, orchestrator.User]
	listUsers      *connect.Client[orchestrator.ListUsersRequest, orchestrator.ListUsersResponse]
	getUser        *connect.Client[orchestrator.GetUserRequest, orchestrator.User]
	listUserRoles  *connect.Client[orchestrator.ListUserRolesRequest, orchestrator.ListUserRolesResponse]
}

// GetCurrentUser calls confirmate.orchestrator.v1.UserManagement.GetCurrentUser.
func (c *userManagementClient) GetCurrentUser(ctx context.Context, req *connect.Request[orchestrator.GetCurrentUserRequest]) (*connect.Response[orchestrator.User], error) {
	return c.getCurrentUser.CallUnary(ctx, req)
}

// ListUsers calls confirmate.orchestrator.v1.UserManagement.ListUsers.
func (c *userManagementClient) ListUsers(ctx context.Context, req *connect.Request[orchestrator.ListUsersRequest]) (*connect.Response[orchestrator.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls confirmate.orchestrator.v1.UserManagement.GetUser.
func (c *userManagementClient) GetUser(ctx context.Context, req *connect.Request[orchestrator.GetUserRequest]) (*connect.Response[orchestrator.User], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListUserRoles calls confirmate.orchestrator.v1.UserManagement.ListUserRoles.
func (c *userManagementClient) ListUserRoles(ctx context.Context, req *connect.Request[orchestrator.ListUserRolesRequest]) (*connect.Response[orchestrator.ListUserRolesResponse], error) {
	return c.listUserRoles.CallUnary(ctx, req)
}

// UserManagementHandler is an implementation of the confirmate.orchestrator.v1.UserManagement
// service.
type UserManagementHandler interface {
	// Returns information about the currently authenticated user
	GetCurrentUser(context.Context, *connect.Request[orchestrator.GetCurrentUserRequest]) (*connect.Response[orchestrator.User], error)
	// Lists users with optional filtering
	ListUsers(context.Context, *connect.Request[orchestrator.ListUsersRequest]) (*connect.Response[orchestrator.ListUsersResponse], error)
	// Retrieves a specific user by their ID. This endpoint is restricted to users with elevated roles, such as admin.
	GetUser(context.Context, *connect.Request[orchestrator.GetUserRequest]) (*connect.Response[orchestrator.User], error)
	// Lists all predefined roles in the system.
	ListUserRoles(context.Context, *connect.Request[orchestrator.ListUserRolesRequest]) (*connect.Response[orchestrator.ListUserRolesResponse], error)
}

// NewUserManagementHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserManagementHandler(svc UserManagementHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userManagementMethods := orchestrator.File_api_orchestrator_user_proto.Services().ByName("UserManagement").Methods()
	userManagementGetCurrentUserHandler := connect.NewUnaryHandler(
		UserManagementGetCurrentUserProcedure,
		svc.GetCurrentUser,
		connect.WithSchema(userManagementMethods.ByName("GetCurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	userManagementListUsersHandler := connect.NewUnaryHandler(
		UserManagementListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userManagementMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userManagementGetUserHandler := connect.NewUnaryHandler(
		UserManagementGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userManagementMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userManagementListUserRolesHandler := connect.NewUnaryHandler(
		UserManagementListUserRolesProcedure,
		svc.ListUserRoles,
		connect.WithSchema(userManagementMethods.ByName("ListUserRoles")),
		connect.WithHandlerOptions(opts...),
	)
	return "/confirmate.orchestrator.v1.UserManagement/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserManagementGetCurrentUserProcedure:
			userManagementGetCurrentUserHandler.ServeHTTP(w, r)
		case UserManagementListUsersProcedure:
			userManagementListUsersHandler.ServeHTTP(w, r)
		case UserManagementGetUserProcedure:
			userManagementGetUserHandler.ServeHTTP(w, r)
		case UserManagementListUserRolesProcedure:
			userManagementListUserRolesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserManagementHandler returns CodeUnimplemented from all methods.
type UnimplementedUserManagementHandler struct{}

func (UnimplementedUserManagementHandler) GetCurrentUser(context.Context, *connect.Request[orchestrator.GetCurrentUserRequest]) (*connect.Response[orchestrator.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.orchestrator.v1.UserManagement.GetCurrentUser is not implemented"))
}

func (UnimplementedUserManagementHandler) ListUsers(context.Context, *connect.Request[orchestrator.ListUsersRequest]) (*connect.Response[orchestrator.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.orchestrator.v1.UserManagement.ListUsers is not implemented"))
}

func (UnimplementedUserManagementHandler) GetUser(context.Context, *connect.Request[orchestrator.GetUserRequest]) (*connect.Response[orchestrator.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.orchestrator.v1.UserManagement.GetUser is not implemented"))
}

func (UnimplementedUserManagementHandler) ListUserRoles(context.Context, *connect.Request[orchestrator.ListUserRolesRequest]) (*connect.Response[orchestrator.ListUserRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("confirmate.orchestrator.v1.UserManagement.ListUserRoles is not implemented"))
}
